### ISSUE TITLE
Package require error

### ISSUE THREAD

**Issue by DJWassink** [jxcore/jxcore#101]
First of all I am pretty new to node/js-backend etc. so excuse me if this is just me screwing it up.
Anyhow I am running into a issue with requirering a socket.io inside a express project. Running the project goes fine with node/unpackaged JXCore but when I package the project and launch it I get the following error in my console.

```
fs.js:676
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
             ^
Error: ENOENT, no such file or directory 'c:\node\webserver1\node_modules\socket
.io\node_modules\socket.io-client\socket.io.js.jx'
    at Object.fs.openSync (fs.js:676:18)
    at fs.readFileSync (fs.js:533:15)
    at Object.<anonymous> (c:\node\webserver1\node_modules\socket.io\lib\index.j
s.jx:29:20)
    at Module._compile (module.js:520:26)
    at Object.Module._extensions..jx (module.js:1362:405)
    at Module.load (module.js:359:33)
    at Function.Module._load (module.js:333:12)
    at Module.require (module.js:372:17)
    at require (module.js:399:17)
    at Object.<anonymous> (c:\node\webserver1\node_modules\socket.io\index.js.jx
:3:18)
```

I am trying to include the socket.io like this:

```
var io = require('socket.io')(server);
```

This works fine normally but somehow breaks in a jxcore package. I tried a few different ways of getting this to work but somehow they all resulted in the same error.

**Comment by ktrzeciaknubisa** [comment]
Anyone who wants to try new packaging partial extraction feature allowing to run packages containing native modules (*.node* files) - see https://github.com/jxcore/jxcore/issues/370#issuecomment-131396697.

**Comment by szy520** [comment]
Warning! ....tests__/test_root/NativeModule.node
Adding a .node (native) file into package may fail the application

**Comment by ktrzeciaknubisa** [comment]
@szy520 https://github.com/jxcore/jxcore/issues/140

**Comment by szy520** [comment]
/media/dx/work/dx/DxBim/dxbim/build/node_modules/redis/node_modules/redis-parser/lib/hiredis.js.jx:7
    this.reader = new hiredis.Reader(options);
                  ^
TypeError: undefined is not a function
    at new HiredisReplyParser (/media/dx/work/dx/DxBim/dxbim/build/node_modules/redis/node_modules/redis-parser/lib/hiredis.js.jx:7:19)
    at Parser (/media/dx/work/dx/DxBim/dxbim/build/node_modules/redis/node_modules/redis-parser/lib/parser.js.jx:49:18)
    at new RedisClient (/media/dx/work/dx/DxBim/dxbim/build/node_modules/redis/index.js.jx:143:25)
    at Object.exports.createClient (/media/dx/work/dx/DxBim/dxbim/build/node_modules/redis/index.js.jx:977:12)
    at new RedisStore (/media/dx/work/dx/DxBim/dxbim/build/node_modules/connect-redis/lib/connect-redis.js.jx:76:27)
    at Object.<anonymous> (/media/dx/work/dx/DxBim/dxbim/build/server/server.js.jx:29:12)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:878:12)
    at startup (node.js:485:18)
    at node.js:1604:3
@ktrzeciaknubisa
