### ISSUE TITLE
JX Packaging with Sails.js

### ISSUE THREAD

**Issue by tiagodexter** [jxcore/jxcore#154]
After i package my app, when I run with JX, it`s returns an error, but when I run without packaging, I don`t have this error.

I'm using these processes:

MacBook-Pro-de-Tiago:~ tiagodexter$ sails new installer
info: Created a new Sails app `installer`!
MacBook-Pro-de-Tiago:installer tiagodexter$ sudo ../Downloads/jx_osx64/jx package app.js installer
MacBook-Pro-de-Tiago:installer tiagodexter$ sudo ../Downloads/jx_osx64/jx installer.jx

/Users/tiagodexter/installer/node_modules/sails/node_modules/captains-log/node_modules/rc/index.js.jx:2
# ! /usr/bin/env node

^
To run an app using `node app.js`, you usually need to have a version of `sails` installed in the same directory as your app.
To do that, run `npm install sails`

Alternatively, if you have sails installed globally (i.e. you did `npm install -g sails`), you can use `sails lift`.
When you run `sails lift`, your app will still use a local `./node_modules/sails` dependency if it exists,
but if it doesn't, the app will run with the global sails instead!

And when I run without package, I have this return.

MacBook-Pro-de-Tiago:installer tiagodexter$ sudo ../Downloads/jx_osx64/jx app.js 
info: 
info: 
info:    Sails              <|
info:    v0.10.5             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---**_--**_---**_--**_---**_--**_
info:  ____---**_--**_---**_--**_---**_--**_-__
info: 
info: Server lifted in `/Users/tiagodexter/installer`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Mon Dec 08 2014 21:09:39 GMT-0200 (BRST)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------

Anyone can help me?

**Comment by stalinb87** [comment]
Hi,
I having the same issue, there is a  solution to this ?

**Comment by ktrzeciaknubisa** [comment]
@stalinb87 which one exactly, because there are few discussed here? JX core packaging with sails or `sudo jx install sails`? Please also mention the platform.

**Comment by stalinb87** [comment]
Sorry, the problem is with JX core packaging with sails

i having this error

/home/sbonilla/Documents/to_save/Projects/ifix/backend/node_modules/sails/node_modules/captains-log/node_modules/rc/index.js.jx:2
#!/usr/bin/env jx
^
To run an app using `node app.js`, you usually need to have a version of `sails` installed in the same directory as your app.
To do that, run `npm install sails`

Alternatively, if you have sails installed globally (i.e. you did `npm install -g sails`), you can use `sails lift`.
When you run `sails lift`, your app will still use a local `./node_modules/sails` dependency if it exists,
but if it doesn't, the app will run with the global sails instead!

I try all the solution that you give, but still having the same problem, i saw that in jpx file property is include "node_modules/sails"

I am using elementary OS with the kernel 3.13.0-43-generic, node version 0.10.34  and jx version 0.10.32

sorry for my bad english

**Comment by ktrzeciaknubisa** [comment]
@stalinb87 Thanks. So it's similar. See above this: 
>There might be few issues stacking here, for example packaged jx probably doesn't handle properly shebang line (#! /usr/bin/env node) placed inside .js file, and this is exactly what you get as error.

this:
> But the main thing is that packing native files (.node) is not a good idea - we talked about this e.g. here: #101. 

and this:
```bash
$ jx package app.js installer -slim node_modules
```
It excludes sails from being packaged.

Finally, after you'll move your jx package into new folder, install sails manually from there:
```bash
$ sudo jx install sails
```

**Comment by stalinb87** [comment]
@ktrzeciaknubisa  Thanks thats work

**Comment by stalinb87** [comment]
@ktrzeciaknubisa  Ohh sorry, in fact i am having the same error that @tiagodexter  i haven't moved my installer but when a did i got this

    return binding.stat(pathModule._makeLong(path));
                 ^
   Error: ENOENT, no such file or directory '/tmp/api/models/.gitkeep'
       at Object.fs.statSync (fs.js:755:18)
       at /tmp/node_modules/include-all/index.js:48:12
       at Array.forEach (native)
       at requireAll (/tmp/node_modules/include-all/index.js:44:9)
       at buildDictionary (/tmp/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
       at Function.module.exports.optional (/tmp/node_modules/sails/node_modules/sails-build-  dictionary/index.js:160:9)
       at Hook.loadModels (/tmp/node_modules/sails/lib/hooks/moduleloader/index.js:261:23)
       at Hook.bound [as loadModels]    (/tmp/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
       at Array.async.auto.models [as 0] (/tmp/node_modules/sails/lib/hooks/orm/load-user-modules.js:23:23)
        at /tmp/node_modules/sails/node_modules/async/lib/async.js:459:38

**Comment by ktrzeciaknubisa** [comment]
Is it possible that you have moved jx package into another machine, where the folder `/tmp/api/models/` does not exist?

**Comment by stalinb87** [comment]
This folder is part of the project, if i create the folder /tmp/api/models/ eventually start asking me for project file, like `api/policeis/isautheticad.js`, and if a added this files eventually i will adding the entire project becaouse always ask for, is like the installer has the reference outside the installer

**Comment by ktrzeciaknubisa** [comment]
@tiagodexter As for the "CERT_HAS_EXPIRED" error - i just accidentally run into the opposite: "CERT_NOT_YET_VALID", and this was due to my machine's date was moved much into the past. So I thought that in your case might be vice versa. Is this possible that your machine's date was much in future?

**Comment by microstrip** [comment]
I am currently encountering the same problem here.
It looks like I have to include "api" folder (and its files) in order to use "jx myapp".

Is there any way jx can run without explicitly use "api" folder?
