### ISSUE TITLE
FreeBSD 9.1 x64 - "This operating system is not supported"

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#156]
JXcore gets installed correctly on FreeBSD 9.1 x64, however there is an error when running:

```bash
root@freebsd92:/root # jx -e "console.log(jxcore.utils.OSInfo())"

_jx_utils.js:83
        throw new Error("This operating system is not supported ("+info+")");
              ^
Error: This operating system is not supported (freebsd-x64)
    at Object.exports.OSInfo (_jx_utils.js:83:15)
    at [eval]:1:26
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:525:26)
    at evalScript (node.js:882:25)
    at startup (node.js:232:7)
    at node.js:2115:1
```

This causes `jx install xxx` not working.

**Some extra info:**

```bash
root@freebsd92:/root # uname -mrsn
FreeBSD freebsd92 9.1-RELEASE amd64
```

**ISO image url:**

ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/amd64/ISO-IMAGES/9.1/FreeBSD-9.1-RELEASE-amd64-disc1.iso

**Comment by ktrzeciaknubisa** [comment]
This is no longer the issue starting from JXcore 0.3.0.0.
