### ISSUE TITLE
After packaging the mean js application using Jxcore, If I copy it to different folder and try to run it, I am getting the following error. However I am able to run it from the project source folder.

### ISSUE THREAD

**Issue by ananda006hg** [jxcore/jxcore#173]
When I try to run using the JX command , I get the following error. But it works fine with grunt command.

E:\JXCORE\myApp>jx newPackage.jx
NODE_ENV is not defined! Using default development environment

E:\JXCORE\myApp\node_modules\mongoose\lib\index.js:323
      throw new mongoose.Error.MissingSchemaError(name);
            ^
MissingSchemaError: Schema hasn't been registered for model "User".
Use mongoose.model(name, schema)
    at Mongoose.model (E:\JXCORE\myApp\node_modules\mongoose\lib\index.js:323:13
)
    at Object.<anonymous> (E:\JXCORE\myApp\config\passport.js.jx:9:29)
    at Module._compile (module.js:525:26)
    at Object.Module._extensions..jx (module.js:1604:6)
    at Module.load (module.js:369:35)
    at Function.Module._load (module.js:336:12)
    at Module.require (module.js:388:17)
    at require (module.js:405:17)
    at Object.<anonymous> (E:\JXCORE\myApp\config\express.js.jx:20:13)
    at Module._compile (module.js:525:26)

**Comment by ktrzeciaknubisa** [comment]
Hi. Which command did you use to create the *newPackage.jx*? With or without `-slim` option?

**Comment by ananda006hg** [comment]
Hi,

I have used the following command  with slim option for packaging.

-->jx package server.js newPackage -slim config,node_modules

Note: later I copied the  package and excluded folders to different location and tried executing .its not running.

**Comment by ktrzeciaknubisa** [comment]
> Note: later I copied the package and excluded folders to different location and tried executing .its not running.

Ok, but did you run copied package from it's new location?

**Comment by ananda006hg** [comment]
Please find the following steps which I had carried out.

1. Executed the command--> "jx package server.js newPackage -slim config,node_modules " in the project source directory.

2. Then executed the command in the same project source directory--->"jx newPackage.jx". Which starts the application.

3. I copied newPackage.jx,node_modules and config folder to some other location and executed the command --->"jx newPackage.jx". But I got the following error.

E:\JXCORE\packagedCode\node_modules\mongoose\lib\index.js:323
      throw new mongoose.Error.MissingSchemaError(name);
            ^
MissingSchemaError: Schema hasn't been registered for model "User".
Use mongoose.model(name, schema)
    at Mongoose.model (E:\JXCORE\packagedCode\node_modules\mongoose\lib\index.js
:323:13)
    at Object.<anonymous> (E:\JXCORE\packagedCode\config\passport.js:7:29)
    at Module._compile (module.js:525:26)
    at Object.Module._extensions..js (module.js:543:10)
    at Module.load (module.js:369:35)
    at Function.Module._load (module.js:336:12)
    at Module.require (module.js:388:17)
    at require (module.js:405:17)
    at Object.<anonymous> (E:\JXCORE\packagedCode\server.js.jx:29:1)
    at Module._compile (module.js:525:26)

**Comment by ktrzeciaknubisa** [comment]
Thank you. What I was trying to ask is whether before 3rd step you changed directory by `cd E:\JXCORE\packagedCode\` (as I understand this is your new location, right?). But now I guess your did that, since you call `jx newPackage.jx`?

I don't know much about MEAN, but there is a thread [MissingSchemaError: Schema hasn't been registered for model “User”](http://stackoverflow.com/questions/20832126/missingschemaerror-schema-hasnt-been-registered-for-model-user) on StackOverflow - maybe you'll find it useful?

**Comment by ananda006hg** [comment]
Hi,

I have resolved the above issue , but now I am getting another issue in express .


E:\JXCORE\nodeJspackedcode\config\express.js.jx:31
        var app = express();
                  ^
TypeError: object is not a function
    at module.exports (E:\JXCORE\nodeJspackedcode\config\express.js.jx:31:12)
    at Object.<anonymous> (E:\JXCORE\nodeJspackedcode\server.js.jx:26:38)
    at Module._compile (module.js:525:26)
    at readX (module.js:1225:4)
    at Object.Module._extensions..jx (module.js:1654:9)
    at Module.load (module.js:369:35)
    at Function.Module._load (module.js:336:12)
    at Function.Module.runMain (module.js:720:12)
    at startup (node.js:323:14)
    at node.js:2115:1

Is there a specific version of express for JXCore ? if  it is please let me know.

thanks
Anand

**Comment by ktrzeciaknubisa** [comment]
May I ask, how did you resolve the previous issue?

As for the new one (with express) - there is no specific version of express for JXcore, however newer express versions were not tested after JXcore version was released, so it might happen, that something goes wrong. For JXcore 2.3.7 you can try some express version released before December 2014. 

Please let us know it that helps.

**Comment by obastemur** [comment]
I think I've already fixed this problem on master. Please reopen if the problem persists.
