### ISSUE TITLE
Expressjs error at express.session

### ISSUE THREAD

**Issue by tulu1688** [jxcore/jxcore#264]
Hi,

I get the error when running my nodejs app.

/home/khaitn/VMTS/Viewer/node_modules/connect/lib/middleware/session/cookie.js.jx:128
    return cookie.serialize(name, val, this.data);
                  ^
TypeError: Object #<Object> has no method 'serialize'
    at Object.Cookie.serialize (/home/khaitn/VMTS/Viewer/node_modules/connect/lib/middleware/session/cookie.js.jx:128:19)
    at ServerResponse.<anonymous> (/home/khaitn/VMTS/Viewer/node_modules/connect/lib/middleware/session.js.jx:277:20)
    at ServerResponse.emit (events.js:92:17)
    at ServerResponse.res.writeHead (/home/khaitn/VMTS/Viewer/node_modules/connect/lib/patch.js.jx:84:36)
    at ServerResponse._implicitHeader (http.js:805:8)
    at ServerResponse.OutgoingMessage.end (http.js:578:10)
    at /home/khaitn/VMTS/Viewer/node_modules/connect/lib/middleware/session.js.jx:292:13
    at process._tickDomainCallback (node.js:808:13)

Pls show me the workaround solution!

**Comment by obastemur** [comment]
@tulu1688 which jxcore version ? 'jx -jxv' 

could you share the repro steps ?

**Comment by ktrzeciaknubisa** [comment]
Yes, definitively we need more info. I've just tested simple express app and it works packaged. 

Your app might be more complex and it looks like it's not about express at all. The file system paths from your log does not fit to express directory structure. At least not the latest. 

From this reason we would use some more details, like:
- `x -jxv` (or is it compiled from sources?)
- express version
- jx package or `-native`

And the best would be few lines of the code.

**Comment by tulu1688** [comment]
@ktrzeciaknubisa thx for your promptly reply.

I'm here to change my nodejs app to jxcore because of Packaging Nodejs app. Hope JxCore work well.

1. jxcore version is: v Beta-0.2.3.7
2. express version: 3.2.4
3. Both jx package or -native fire this error
4. I'm using Ubuntu 14.04.2 LTS

And here my some source code:
var express = require('express'),
	ClusterStore = require('strong-cluster-connect-store')(express),
	cluster = require('cluster'),
	i18n = require('i18next'),
	http = require('http'),
	path = require('path'),
	io = require('socket.io'),
	os = require('os'),
	fs = require('fs'),
	redis = require('socket.io/node_modules/redis'),
	util = require('util'),
	passport = require('passport'),
	flash = require('connect-flash'),
	LocalStrategy = require('passport-local').Strategy,
	cf = require('./config.js'),
	dir = __dirname,
	fe = require('./frontend_adapter.js'),
	dal = require('./dal'),
	JSFtp = require("jsftp"),
	config = require('./config.js'),
	captcha = require('captcha'),
	compression = require('compression'),
	crypto = require('cryptojs').Crypto;
var noCache = require('connect-nocache')();

dal.setRPC(config.RPC_SERVICE_ADDR, config.BROAD_CAST_SERVICE_ADDRS, config.RPC_CAPNP_FILE); // setup RPC

i18n.init({
	saveMissing: true,
	debug: false
});

var app = express();
var redisClient = require("redis").createClient();
var RedisStore = require('socket.io/lib/stores/redis'),
	redis = require('socket.io/node_modules/redis'),
	pub = redis.createClient(),
	sub = redis.createClient(),
	client = redis.createClient();

var alertLoginFail;
// all environments
app.use(i18n.handle);
app.set('port', process.env.PORT || cf.SOCKET_IO_PORT);
app.set('views', __dirname + '/views');
app.set('view engine', 'jade');

app.use(express.bodyParser({
	keepExtensions: true,
	uploadDir: './public/uploads',
	limit: '10mb'
}));

app.use(express.methodOverride());
app.use(express.cookieParser());
app.use(express.session({
	store: new ClusterStore(),
	secret: 'KTN'
}));
app.use(passport.initialize());
app.use(passport.session());
app.use(flash());
app.use(app.router);
app.use(express.static(path.join(__dirname, 'public')));
app.use(captcha({ url: '/captcha.jpg', color: '#FFFF00', background: 'rgb(0,153,204)' })); // captcha params

Regards,

**Comment by ktrzeciaknubisa** [comment]
Thanks for the code. Indeed it gets complex with so many dependencies. I was able to run it but only with some dependencies disabled, since e.g. `socket.io` version is also not specified (the newest does not contain `redis` module as your code suggests). And it went fine, so I haven't meet your problem still.

However for express@3.2.4 I can see paths from your log, so now it does make sense.

I would suggest you to use the newest JXcore 0.3.0 (taken from master branch of this repo and compiled) since it contains many fixes concerning packaging (and not only of course). Then we'll see if the problem persists.
