### ISSUE TITLE
JX Encounters TypeError While Node Doesn't In Express App

### ISSUE THREAD

**Issue by DLLarson** [jxcore/jxcore#276]
I'm trying to provide a better bug report but am having trouble refining it so I thought I'd post what I'm seeing in case it's clear to somebody else. 

Here's what I'm seeing when I run our application:
```
dlarson@u1404ssd:~/andy/map3/tangerine/usr/local/tangerine$ NODE_ENV=production node server/server.js 
Warning: connection.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.

>> RUNS FINE VIA WEB BROWSER

dlarson@u1404ssd:~/andy/map3/tangerine/usr/local/tangerine$ NODE_ENV=production jx server/server.js 
Warning: connection.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.

>> CRASHES WITH JX

buffer.js:157
      throw new TypeError('First argument needs to be a number, '
            ^
TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:157:13)
    at fs.js:208:16
    at Object.oncomplete (fs.js:83:15)

dlarson@u1404ssd:~/tools/jxcore$ jx -v
v0.10.38
dlarson@u1404ssd:~/tools/jxcore$ node -v
v0.10.30
```

I'm running a very recent build commit 4883b1b with default `./configure` settings on Ubuntu 14.04LTS x64.

-Dale

**Comment by DLLarson** [comment]
I just pulled the very latest commit e455962a and it does NOT fail.

Closing the issue.
