### ISSUE TITLE
Simple Node App Using i18next Fails When Run as a Package

### ISSUE THREAD

**Issue by DLLarson** [jxcore/jxcore#282]
I've tried running JXcore against a V8 debugger but the command:
```
jx debug server/server.js
```
and
```
jx debug mapgw.jx
```
just hangs with a `connecting...` message that doesn't seem to line up with what the docs say I should see. 

In addition, using the node `--debug*` commands don't even work:
```
dlarson@u1404ssd:~/andy/tangerine$ jx --debug-brk=9222 server/server.js 
Segmentation fault (core dumped)
```
I'm attempting to find out why my express based application runs fine with `jx server/server.js` (I'm dumping the i18n object near the error as described at the end of this report): 
```
dlarson@u1404ssd:~/andy/tangerine$ NODE_ENV=production jx server/server.js
i18n object =>  {
    "version": "1.7.4",
    "clientVersion": "1.7.3",
    "pluralExtensions": {
        "rules": {
            "ach": {
                "name": "Acholi",
                "numbers": [
                    1,
                    2
                ]
            },
            "af": {
                "name": "Afrikaans",
                "numbers": [
                    1,
                    2
                ]
            },
			:
			:
			:
            "zh": {
                "name": "Chinese",
                "numbers": [
                    1
                ]
            }
        }
    },
    "sync": {},
    "functions": {
        "cookie": {}
    },
    "options": {
        "load": "all",
        "preload": [],
        "lowerCaseLng": false,
        "returnObjectTrees": false,
        "fallbackLng": [
            "dev"
        ],
        "fallbackNS": [],
        "detectLngQS": "setLng",
        "ns": "translation",
        "fallbackOnNull": true,
        "fallbackOnEmpty": false,
        "fallbackToDefaultNS": false,
        "nsseparator": ":",
        "keyseparator": ".",
        "selectorAttr": "data-i18n",
        "debug": false,
        "resGetPath": "locales/__lng__/__ns__.json",
        "resPostPath": "locales/add/__lng__/__ns__",
        "getAsync": true,
        "postAsync": true,
        "useLocalStorage": false,
        "localStorageExpirationTime": 604800000,
        "dynamicLoad": false,
        "sendMissing": false,
        "sendMissingTo": "fallback",
        "sendType": "POST",
        "interpolationPrefix": "__",
        "interpolationSuffix": "__",
        "reusePrefix": "$t(",
        "reuseSuffix": ")",
        "pluralSuffix": "_plural",
        "pluralNotFound": "plural_not_found0.8751819115132093",
        "contextNotFound": "context_not_found0.32565796095877886",
        "escapeInterpolation": false,
        "setJqueryExt": true,
        "defaultValueFromContent": true,
        "useDataAttrOptions": false,
        "useCookie": true,
        "cookieName": "i18next",
        "shortcutFunction": "sprintf"
    }
}
Warning: connection.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
### I CAN NOW ACCESS THE WEB GUI
```
However when I run against the packaged version I get:
```
dlarson@u1404ssd:~/andy/tangerine$ NODE_ENV=production jx mapgw.jx
i18n object =>  {
    "$JXP": {
        "name": "mapgw",
        "version": "1.0",
        "author": "",
        "description": "",
        "company": "",
        "website": "",
        "package": "/home/dlarson/andy/tangerine/package.json",
        "startup": "./server/server.js",
        "execute": null,
        "extract": false,
        "output": "mapgw.jx",
        "files": true,
        "assets": [
            ".gitattributes",
            ".gitignore",
            "Makefile",
            "README.md",
			:
			:
			:
            "views/toobusy.jade",
            "views/updating.jade",
            "views/viewdefvalidator.jade"
        ],
        "preInstall": null,
        "library": true,
        "readme_file": "README.md",
        "fs_reach_sources": true
    }
}

/home/dlarson/andy/tangerine/server/lib/translator/i18next.js.jx:94
        i18n.backend(templateBackend);
             ^
TypeError: Object #<Object> has no method 'backend'
    at Object.init (/home/dlarson/andy/tangerine/server/lib/translator/i18next.js.jx:94:14)
    at Object.<anonymous> (/home/dlarson/andy/tangerine/server/server.js.jx:129:8)
    at Module._compile (module.js:519:26)
    at readX (module.js:1235:5)
    at Object.Module._extensions..jx (module.js:1637:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:735:12)
    at startup (node.js:378:18)
    at node.js:2294:3
### Program exits
dlarson@u1404ssd:~/andy/tangerine$ 
```
For whatever reason the i18n object looks like the `mapgw.jxp` project file sans the `.js` and `.json` files.

The error occurs when executing the following code excerpt found in our file `./server/lib/translator/i18next.js`:
```
var i18n = require('i18next')
console.log(util.format('i18n object => ', JSON.stringify(i18n, null, 4))); //@@@@@@
i18n.backend(templateBackend);
```
I'm looking at this as my next step to get our application running on Android. My thinking is: if the code doesn't run as a JXcore package, it won't run packaged under the Android sample code.

-Dale

**Comment by obastemur** [comment]
The first issue with 'MemoryStore not designed for production' message is something with the underlying express module [more on this](http://stackoverflow.com/questions/10760620/using-memorystore-in-production) As for the packaging, you need to keep the files in assets (under jxp file) those you want to read. 

Do you have a repro steps so we could check it?

**Comment by DLLarson** [comment]
>The first issue with 'MemoryStore not designed for production' message is something with the underlying express module 

This one is just an artifact. The web site works with it even though the issue is presented. I'm ignoring it for now. I included it since it was output of the run and may have been important.

> Do you have a repro steps so we could check it?

Not that I can publicly share--hence my plea for debugging help.

I can say that all the files packaged are under the directory where the `mapgw.jxp` file is. This includes the `node_modules` folder that has `i18next`.

It sounds like my hope that it's obvious from my posting won't bear fruit so I'll see what I can to to extract it down to a simpler form.

Thanks!
-Dale

**Comment by DLLarson** [comment]
I have a minimal reproduction of the problem. The source code is here:

https://github.com/DLLarson/jxcore-android-basics/tree/jxcorebug282

When the app is run directly with `jx server/server.js' it doesn't produce an error and the test exits fine after printing the `i18next` object.

If the app is run as follows the problem occurs:
```
$ jx package server/server.js i18nfail
$ jx i18nfail.jx
i18n object =>  {
    "$JXP": {
        "name": "i18nfail",
        "version": "1.0",
        "author": "",
        "description": "",
        "company": "",
        "website": "",
        "package": null,
        "startup": "./server/server.js",
        "execute": null,
        "extract": false,
        "output": "i18nfail.jx",
        "files": true,
        "assets": [
            "node_modules/i18next/.npmignore",
            "node_modules/i18next/.travis.yml",
            "node_modules/i18next/Makefile",
            "node_modules/i18next/README.md",
            "node_modules/i18next/backends/couchDb/.npmignore",
            "node_modules/i18next/backends/gettext/.npmignore",
            "node_modules/i18next/backends/mongoDb/.npmignore",
            "node_modules/i18next/backends/redis/.npmignore",
            "node_modules/i18next/backends/remoteSync/.npmignore",
            "node_modules/i18next/backends/yaml/.npmignore",
            "node_modules/i18next/lib/dep/i18nextWT/css/i18nextWT.css",
            "node_modules/i18next/lib/dep/i18nextWT/favicon.ico",
            "node_modules/i18next/lib/dep/i18nextWT/font/fontawesome-webfont.eot",
            "node_modules/i18next/lib/dep/i18nextWT/font/fontawesome-webfont.svg",
            "node_modules/i18next/lib/dep/i18nextWT/font/fontawesome-webfont.ttf",
            "node_modules/i18next/lib/dep/i18nextWT/font/fontawesome-webfont.woff",
            "node_modules/i18next/lib/dep/i18nextWT/img/chosen-sprite.png",
            "node_modules/i18next/lib/dep/i18nextWT/index.html",
            "node_modules/i18next/license",
            "node_modules/i18next/node_modules/cookies/.npmignore",
            "node_modules/i18next/node_modules/cookies/History.md",
            "node_modules/i18next/node_modules/cookies/LICENSE.txt",
            "node_modules/i18next/node_modules/cookies/README.md",
            "node_modules/i18next/node_modules/cookies/node_modules/keygrip/.npmignore",
            "node_modules/i18next/node_modules/cookies/node_modules/keygrip/.travis.yml",
            "node_modules/i18next/node_modules/cookies/node_modules/keygrip/LICENSE.txt",
            "node_modules/i18next/node_modules/cookies/node_modules/keygrip/README.md",
            "node_modules/i18next/releasenotes.md",
            "node_modules/i18next/test/jade/test.jade",
            "node_modules/i18next/test/locales/en-US/ns.test.po",
            "node_modules/i18next/test/locales/en-US/ns.test.yml",
            "node_modules/i18next/test/mocha.opts",
            "node_modules/i18next/test/readme.txt"
        ],
        "preInstall": null,
        "library": true,
        "fs_reach_sources": true
    }
}

/home/dlarson/android/tangtest/server/lib/translator/i18next.js.jx:12
        i18n.backend(templateBackend);      // <<==== ERROR OCCURS HERE!!!!!!!
             ^
TypeError: Object #<Object> has no method 'backend'
    at Object.init (/home/dlarson/android/tangtest/server/lib/translator/i18next.js.jx:12:14)
    at Object.<anonymous> (/home/dlarson/android/tangtest/server/server.js.jx:5:8)
    at Module._compile (module.js:519:26)
    at readX (module.js:1235:5)
    at Object.Module._extensions..jx (module.js:1637:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:735:12)
    at startup (node.js:378:18)
    at node.js:2294:3
$ 
```

I'm really hoping this helps.

-Dale

**Comment by obastemur** [comment]
this has been a very good addition to our test base. The file under `server/lib/translator` is named as `i18next.js` and requires 'i18next' (itself) However, it should skip itself and search for other references. 

I've added this bug into my list. In the mean time, you can simply rename i18next.js file under server/lib/translator to some another name and move on.

**Comment by DLLarson** [comment]
>you can simply rename i18next.js file under server/lib/translator to some another name and move on.

Renaming the file did get me past that error---alas I've hit another in the full application:
```
Warning: connection.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.


node.js:847
            throw ee;
                  ^
TypeError: Object #<Object> has no method 'serialize'
    at Object.Cookie.serialize (/home/dlarson/android/tangerine/node_modules/express/node_modules/connect/lib/middleware/session/cookie.js.jx:128:19)
    at ServerResponse.<anonymous> (/home/dlarson/android/tangerine/node_modules/express/node_modules/connect/lib/middleware/session.js.jx:271:20)
    at ServerResponse.emit (events.js:79:15)
    at ServerResponse.res.writeHead (/home/dlarson/android/tangerine/node_modules/express/node_modules/connect/lib/patch.js.jx:74:36)
    at ServerResponse._implicitHeader (http.js:739:8)
    at ServerResponse.OutgoingMessage.end (http.js:535:10)
    at /home/dlarson/android/tangerine/node_modules/express/node_modules/connect/lib/middleware/session.js.jx:286:13
    at /home/dlarson/android/tangerine/node_modules/express/node_modules/connect/lib/middleware/session/memory.js.jx:74:11
    at process._tickCallback (node.js:837:13)
```
Just thought I'd share that since it seems so similar.

I may just need to wait until there is a fix before proceeding. I'd rather not track down the same error again.

-Dale

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/commit/a30cb50b0aa3f2ad159073132f38e5b81f99b1f9 should fix the previously discussed issue.

**Comment by DLLarson** [comment]
Verified working.

Thanks a zillion! 

Next I can move onto getting it all up on Android.

-Dale
