### ISSUE TITLE
Error running jx file after making the package

### ISSUE THREAD

**Issue by xueenda** [jxcore/jxcore#289]
jx server.js works fine, but after making the package. The following error occurs:
jx package server.js profile
jx profile.jx

/Users/endaxue/workspace/profile/node_modules/passport-linkedin/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js.jx:77
  this._oauth = new OAuth(options.requestTokenURL, options.accessTokenURL,
                ^
TypeError: undefined is not a function
    at Strategy.OAuthStrategy (/Users/endaxue/workspace/profile/node_modules/passport-linkedin/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js.jx:77:17)
    at new Strategy (/Users/endaxue/workspace/profile/node_modules/passport-linkedin/lib/passport-linkedin/strategy.js.jx:53:17)
    at module.exports (/Users/endaxue/workspace/profile/config/passport.js.jx:165:16)
    at Object.<anonymous> (/Users/endaxue/workspace/profile/server.js.jx:63:29)
    at Module._compile (module.js:525:26)
    at readX (module.js:1225:4)
    at Object.Module._extensions..jx (module.js:1654:9)
    at Module.load (module.js:369:35)
    at Function.Module._load (module.js:336:12)
    at Function.Module.runMain (module.js:720:12)

**Comment by xueenda** [comment]
I make a package for another project. Still has error:

/Users/endaxue/workspace/chat/config/express.js.jx:49
  app.use(express.static(config.root + '/public'));
                        ^
TypeError: Object #<Object> has no method 'static'
    at module.exports (/Users/endaxue/workspace/chat/config/express.js.jx:49:25)
    at Object.<anonymous> (/Users/endaxue/workspace/chat/server.js.jx:47:28)
    at Module._compile (module.js:525:26)
    at readX (module.js:1225:4)
    at Object.Module._extensions..jx (module.js:1654:9)
    at Module.load (module.js:369:35)
    at Function.Module._load (module.js:336:12)
    at Function.Module.runMain (module.js:720:12)
    at startup (node.js:323:14)
    at node.js:2115:1

**Comment by xueenda** [comment]
jx -jxv
v Beta-0.2.3.7

**Comment by xueenda** [comment]
BTW
Could you remove /example/ or /examples/ from node_modules folder? They are just examples of certain library and useless for the package.

**Comment by ktrzeciaknubisa** [comment]
Hi, could you share minimal samples for issue reproduction? The less dependencies, the better.

> Could you remove /example/ or /examples/ from node_modules folder?

Do you mean while creating a jx package? The `-slim` switch can be used for that:
```bash
$ jx package server.js profile -slim example,examples
```

**Comment by ktrzeciaknubisa** [comment]
Closing due to no activity. If the problem comes back, we may reopen.
