### ISSUE TITLE
In packaged .exe require fails when running in the different folder

### ISSUE THREAD

**Issue by sergn-n** [jxcore/jxcore#330]
Windows 7 x32/x64 download, jxv 0.3.0.0 V8.
package 
```javascript
{
	"name": "packedApp",
	"version": "1.0",
	"author": "",
	"description": "",
	"company": "",
	"website": "",
	"package": null,
	"startup": "myApp.js",
	"execute": null,
	"extract": false,
	"output": "packedApp.jx",
	"files": [
		"myApp.js",
		"node_modules\\mi\\index.js",
		"node_modules\\mi\\lib\\mi.js"
	],
	"assets": [],
	"preInstall": null,
	"library": true,
	"fs_reach_sources": true,
	"native": true
}
```
myApp.js 
```javascript
var mi = require ('mi');
//var ex = require ('express');
console.log('myApp OK');
```
index.js 
```javascript
console.log('myApp: mi-index');
// fails in jx-package
var mil = require('./lib/mi');
```
mi.js 
```javascript
console.log('myApp: mi-./lib/mi');
```
When packedApp.exe is copied to  and executed from other folder, it fails
```
 F:\tmp\node.js\jx_test\_release>packedApp.exe
myApp: mi-index

fs.js:740
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'F:\tmp\node.js\jx_test\_release\node_m
odules'
    at Object.fs.lstatSync (fs.js:740:18)
    at Object.realpathSync (fs.js:1357:21)
    at tryFile (module.js:119:15)
    at tryExtensions (module.js:127:20)
    at Function.Module._findPath (module.js:162:20)
    at Function.Module._oldRes (module.js:685:25)
    at Function.Module._resolveFilename (module.js:1544:17)
    at Function.Module._load (module.js:268:25)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)
```
The same under v 0.2.3.7. runs OK.

**Comment by ktrzeciaknubisa** [comment]
Thanks for the details. I can confirm the problem on Windows, while It seems working on unix systems.

**Comment by ktrzeciaknubisa** [comment]
From what I can tell till now, this is much related with #304. 

@sergn-n You can try to write *node_modules\dummy.txt*, pack it too and this should work for you. Worked for me.

**Comment by ktrzeciaknubisa** [comment]
Of course! This is just a workaround until we post a fix :)

**Comment by ktrzeciaknubisa** [comment]
dummy.txt needed no more :)
