### ISSUE TITLE
JXCore packaging and paths

### ISSUE THREAD

**Issue by tobibrandenberg** [jxcore/jxcore#35]
Hi!

I wanted to use JXCore with mongoose, but if I package the app and try to run it, it throws:

<code>fs.js:467
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './var/webapp/node_modules/mongoose/node_modules/muri/lib/../package.json'
    at Object.fs.openSync (fs.js:467:18)
    at Object.fs.readFileSync (fs.js:324:15)
    at Object.<anonymous> (./var/webapp/node_modules/mongoose/node_modules/muri/lib/index.js.jx:236:17)
    at Module._compile (module.js:495:26)
    at Object.Module._extensions..jx (module.js:1178:439)
    at Module.load (module.js:379:33)
    at Function.Module._load (module.js:331:12)
    at Module.require (module.js:392:17)
    at require (module.js:410:17)
    at Object.<anonymous> (./var/webapp/node_modules/mongoose/node_modules/muri/index.js.jx:3:28)</code>

even if the file (package.json) exists and is readable - same issue under win7, but there it seems to concatenate paths (e.g. "ENOENT, no such file or directory 'C:\app\web\trunk\dist\C:\app\web\trunk\dist\node_modules\mongoose\node_modules\muri\package.json'"

**Comment by zeeshanjan82** [comment]
I am using sequelize ORM and everything works fine when I run my application using node but after converting the node service into a .exe file and when I run it in windows. I get error in the following line:
var model = sequelize.import(path.join(__dirname, file));
I am not sure if it is related to the discussion but I am not able to import the model files in sequelize when running jxcore exe
