### ISSUE TITLE
Updating Node.JS with JXCore?

### ISSUE THREAD

**Issue by Committing** [jxcore/jxcore#392]
Hi

I'm getting this error when trying to use the Steam API:

------------------------------------------------------------------------------------------------------------
var cryptedSessKey = require('crypto').publicEncrypt(fs.readFileSync(__dirna
^
TypeError: Object # has no method 'publicEncrypt'
at SteamClient.handlers.(anonymous function) (/usr/local/psa/var/modules/jxcore-support/native_modules/node_modules/steam/lib/steam_client.js:150:42)
at SteamClient._netMsgReceived (/usr/local/psa/var/modules/jxcore-support/native_modules/node_modules/steam/lib/steam_client.js:106:26)
at Connection.emit (events.js:82:15)
at Connection._readPacket (/usr/local/psa/var/modules/jxcore-support/native_modules/node_modules/steam/lib/connection.js:50:8)
at Connection.emit (events.js:79:15)
at emitReadable_ (_stream_readable.js:383:10)
at emitReadable (_stream_readable.js:379:5)
at readableAddChunk (_stream_readable.js:143:31)
at Connection.Readable.push (_stream_readable.js:107:10)
at TCP.onread (net.js:489:18)
Spawner error:	Application exited by itself with code: 8
Spawner info:	Subscribing is delayed by 2000 ms.
Spawner info:	Subscribed successfully: Successfully subscribed process 25525 to the monitor.

------------------------------------------------------------------------------------------------------------

The fix is to apparently upgrade my node.js to version v0.12.

How can I do this?

I have the lastest version of JXCore (Installed v Beta-0.3.0.2).

Can you help me?

Thank you

Jack

**Comment by plika** [comment]
JXcore v 0.3 is based on Node 0.10. AFAIK that module has node 0.10 compatible version too. You should use that. We are planning to bring new crypto API from 0.12 soon.

**Comment by Committing** [comment]
Thanks for the response. I had a look at some other Steam Modules but they didn't have the functions I need.

Is there no way to run an update command in ~/node-latest-install? Or will it just break down under a later version? (Or is it not as simple as that!)

Thanks a lot

**Comment by obastemur** [comment]
JXcore = node.JS + additional features + mobile, iot

You can update to latest node but for the pluses above we can't do much. As @plika mentioned we will be working on separate branch for node 0.12 soon

**Comment by Committing** [comment]
Thanks for the response. I ended up just renting a cheap node.js server.

JXcore is awesome - keep it up!

**Comment by obastemur** [comment]
Thanks for the update
