### ISSUE TITLE
Error: Invalid access to memory location.

### ISSUE THREAD

**Issue by ZeevM3** [jxcore/jxcore#396]
I installed another jx over an existing one so i could build versions for both x64 and x86.
I have several projects, all present new errors i haven't seen before:
1. mongoose package presents a new error: 
Error: Invalid access to memory \....location.mongoose\node_modules\mongodb\node_modules\bson\build\release\bson.node
js-bson: Failed to load c++ bson extension, using pure JS version

2. Most important error, is this:
TypeError: Cannot set property 'o' of undefined
    at Object.<anonymous> (fullpathtoproject\node_modules\express\node_modules\debug\node.js.jx:72:22)
    at Module._compile (module.js:519:26)
    at Object.Module._extensions..jx (module.js:1637:7)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)
    at Object.<anonymous> (fullpathtoproject\node_modules\express\node_modules\connect\node_modules\body-parser\
lib\types\json.js.jx:15:13)
    at Module._compile (module.js:519:26)
    at Object.Module._extensions..jx (module.js:1637:7)

project is run with node without any issues.
What is causing this problem with jxcore?
i tried installing v8 both x64 and x86

**Comment by ZeevM3** [comment]
an update:
I create a virtual x86 machine to try the building process from there.
I was able to reproduce the problem, with a clean jxcore installation and the same node.js files.

Something isn't compiling right in this system.

**Comment by ZeevM3** [comment]
Another update:
When installed the older version(0.2.3.7 ) it built and run successfully.

Something in that old version, that has a batch script file manage to work while in the newer version it fails.

**Comment by obastemur** [comment]
@ZeevM3 thanks for the details. /cc @ktrzeciaknubisa

**Comment by ZeevM3** [comment]
The problem is not resolved as i said previously.
Yes the code can compile and RUN when done through a x86 machine, but there are some weird errors.

This Portal project is using express and no site is getting open.
This is the error:
500 Error: ENOENT, no such file or directory 'C:\Program Files\Portal\x86\bin\node_modules'
   at Object.fs.lstatSync (fs.js:742:18)
   at Object.realpathSync (fs.js:1359:21)
   at C:\Program Files\Portal\x86\bin\node_modules\jade\node_modules\uglify-js\tools\node.js.jx:38:15
   at Array.map (native)
   at Object.<anonymous> (C:\Program Files\Portal\x86\bin\node_modules\jade\node_modules\uglify-js\tools\node.js.jx:37:3)
   at Module._compile (module.js:525:26)
   at Object.Module._extensions..jx (module.js:1604:6)
   at Module.load (module.js:369:35)
   at Function.Module._load (module.js:336:12)
   at Module.require (module.js:388:17)
   at require (module.js:405:17)

**Comment by ktrzeciaknubisa** [comment]
We're still looking at it.

**Comment by ZeevM3** [comment]
It's cool, i wanna help so if you need any more information or something talk to me.

Currently the status is this: 
2 machines:
1. x64 - Same code, Same jxcore version - Compiles and run on x64 only no errors.
2. x86 - Same code, Same jxcore version - Compiles and run on x86 only with the error given above.

**Comment by ktrzeciaknubisa** [comment]
Thank you! Might be also helpful (faster) if you could provide with minimal sample for reproduction :)

**Comment by ZeevM3** [comment]
unfortunately this code can't be public.
But it seems that it's having problems with express package, or Jade.
My 2nd project is pretty much identitcal only it doesn't have express on.

You can try packaging an express project on x86 machine with some test jade file and it'll reproduce the error.

**Comment by ZeevM3** [comment]
I take that back...
i have no idea what's causing this.
At first i thought the x64 works fine, but now that i moved the exe files to a different machine(Where the path it yelled about on the x86 Don't exsist) and i receive the same error...

Something in the jxcore version that i installed caused this, and i have no idea what

**Comment by obastemur** [comment]
Can you try something minimalistic with jade and let us know ?

**Comment by ZeevM3** [comment]
the 'i have no idea...' part, means that i'm basically using the version i had few days ago and it used to work.

So, something i changed ruined it. but the version supposed to function right, so i have no idea :package:

**Comment by ZeevM3** [comment]
After many annoying hours, i've found the cause.
I had to reclone the project to previous version and have a look around and found out my JADE got updated from version 1.3.0 which works! to version 1.11.0 which presents the error i wrote you.

That's the cause of the problem.

**Comment by ktrzeciaknubisa** [comment]
Thanks @ZeevM3 . This is quite a tip. Are you able to point out, what to call in order to trigger the error? I mean does `require('jade')` make it failing or any other usage?

**Comment by ZeevM3** [comment]
I can't tell when or where exactly it occurs, but i can tell you that every page i try to load results in the same error message.

the error comes from inner modules that i don't know.
I'm guessing it has to do with getting the paths of the jade files, i assume the new jade package isn't compiled with jxcore the way it used to and some of the paths are ignored(or all of the paths).

**Comment by ktrzeciaknubisa** [comment]
@ZeevM3 Did you try to use jx 3.0.3 from master branch? Are you able to compile it from sources and to check it out?

**Comment by ZeevM3** [comment]
Hi,
I'm good with the old Jade version, i don't need any further assistance, everything is fine now that i returned to the old version.

But thought you might like to hear it has some bugs with jxcore

**Comment by ktrzeciaknubisa** [comment]
Hi @ZeevM3 JXcore 3.0.3 is released. You might want to check if it works with the latest Jade.
