### ISSUE TITLE
AeroSpike DB Connector

### ISSUE THREAD

**Issue by innovocell** [jxcore/jxcore#397]
Hi,
I'm trying to use jxcore to multitask Tasks with my AeroSpike DB but when I try to load the AeroSpike module I get the following error:

node.js:670
    var gpath = process._dlopen(module, filename);
                        ^
Error: /var/www/node_modules/aerospike/build/Release/aerospike.node: undefined symbol: node_module_register
    at Object.process.dlopen [as .node] (node.js:670:25)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)
    at Object.<anonymous> (/var/www/node_modules/aerospike/lib/aerospike.js:1:106)
    at Module._compile (module.js:519:26)
    at Object.Module._extensions..js (module.js:549:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)

It works perfectly in node.js.

Thanks
Rafi

**Comment by ktrzeciaknubisa** [comment]
Just in case if you installed the aerospike with `npm install` - you should try with `jx install`.

**Comment by innovocell** [comment]
Thanks. that's seem to have solved my problem.

Rafi
