### ISSUE TITLE
Package a meteor app

### ISSUE THREAD

**Issue by guillermojmc** [jxcore/jxcore#407]
I tried to package a meteor app using demeteorizer, considering the above [#112](https://github.com/jxcore/jxcore/issues/112), [#113](https://github.com/jxcore/jxcore/issues/113)

```
meteor create test
cd test
demeteorizer
cd .demeteorized
```

I added this at the top of main.js
```
if (process.isPackaged) {
    process.argv.unshift(null);
}
```

This works fine, even with the ```-native``` option
```
jx install
jx package main.js test -slim node_modules
jx test.jx
```

but my code is still there, I move the test.jx entoces its own folder
```
mkdir folder
mv test.jx ./folder
```

and I get this error ```jx ./folder/test.jx```
```
/Users/guillermojmc/test/.demeteorized/folder/main.js.jx:12
process.chdir(require('path').join(__dirname, 'programs', 'server'));
        ^
Error: ENOENT, no such file or directory ''
    at Object.<anonymous> (/Users/guillermojmc/test/.demeteorized/folder/main.js.jx:12:9)
    at Module._compile (module.js:519:26)
    at readX (module.js:1272:5)
    at Object.Module._extensions..jx (module.js:1699:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:737:12)
    at startup (node.js:380:18)
    at node.js:2440:3
```

and this using ```./folder/test```
```
/Users/guillermojmc/test/.demeteorized/folder/main.js.jx:12
process.chdir(require('path').join(__dirname, 'programs', 'server'));
        ^
Error: ENOENT, no such file or directory ''
    at Object.<anonymous> (/Users/guillermojmc/test/.demeteorized/folder/main.js.jx:12:9)
    at Module._compile (module.js:519:26)
    at readX (module.js:1272:5)
    at Object.Module._extensions..jx (module.js:1699:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:519:26)
```

**Comment by ktrzeciaknubisa** [comment]
Hi, your calling `process.chdir`. If this is virtual path (embedded inside a package) then not a file system. This cannot work. However I guess we should output a warning instead of allowing an error to be thrown.

**Comment by ktrzeciaknubisa** [comment]
Hi, I was trying to demeteorize an app myself and to run with node/jxcore, but it hangs out in the console for me, so I didn't even have a chance to try it packaged. Which meteor/demeteorize version are you using?
