### ISSUE TITLE
Packaging with ectjs

### ISSUE THREAD

**Issue by fithwith** [jxcore/jxcore#422]
I'm trying to pack my app and it give me this error when trying to access a web page.
the problem is related to ectjs which is a template engine.
http://ectjs.com/

Error: watch ENOENT
 at errnoException (fs.js:1131:11)
 at FSWatcher.start (fs.js:1163:11)
 at Object.fs.watch (fs.js:1188:11)
 at [object Object].TemplateContext.load (D:\Users\bb14193\Downloads\node_modules\ect\lib\ect.js.jx:355:27)
 at [object Object].TemplateContext.render (D:\Users\bb14193\Downloads\node_modules\ect\lib\ect.js.jx:369:25)
 at View.render (D:\Users\bb14193\Downloads\node_modules\ect\lib\ect.js.jx:416:34)
 at View.render (D:\Users\bb14193\Downloads\node_modules\express\lib\view.js.jx:127:8)
 at tryRender (D:\Users\bb14193\Downloads\node_modules\express\lib\application.js.jx:640:10)
 at EventEmitter.render (D:\Users\bb14193\Downloads\node_modules\express\lib\application.js.jx:592:3)
 at ServerResponse.render (D:\Users\bb14193\Downloads\node_modules\express\lib\response.js.jx:962:7)
 at app.get.req.session.user (D:\Users\bb14193\Downloads\app.js.jx:42:7)
 at Layer.handle [as handle_request] (D:\Users\bb14193\Downloads\node_modules\express\lib\router\layer.js.jx:96:5)
 at next (D:\Users\bb14193\Downloads\node_modules\express\lib\router\route.js.jx:132:13)
 at Route.dispatch (D:\Users\bb14193\Downloads\node_modules\express\lib\router\route.js.jx:113:3)
 at Layer.handle [as handle_request] (D:\Users\bb14193\Downloads\node_modules\express\lib\router\layer.js.jx:96:5)
 at D:\Users\bb14193\Downloads\node_modules\express\lib\router\index.js.jx:278:22
 at Function.process_params (D:\Users\bb14193\Downloads\node_modules\express\lib\router\index.js.jx:331:12)
 at next (D:\Users\bb14193\Downloads\node_modules\express\lib\router\index.js.jx:272:10)
 at Object.<anonymous> (D:\Users\bb14193\Downloads\node_modules\express-session\index.js.jx:434:7)
 at Object.immediate._onImmediate (timers.js:380:16)
 at processImmediate [as _immediateCallback] (timers.js:362:15)

**Comment by ktrzeciaknubisa** [comment]
I'm not familiar much with ectjs, but if there is a case, when it wants to watch files/folders which are not on real file system (because they are packaged) - this has to fail.

Are you able to debug it (some console.log() at `node_modules\ect\lib\ect.js:355:27`) and tell which file/folder is about to be watched? Then we would know if that folder needs to stay out of the package.

**Comment by fithwith** [comment]
yes its the folder /views, in ectjs we have to specify the root folder for the templates using this instrcution:
var renderer = ECT({ root : process.cwd()+"/views", ext : '.ect'});

so for my case all the templates are inside /views.

when I add the views folder with the jx.exe its working well, but for my case I don't want that my end users be able to see the templates.

**Comment by fithwith** [comment]
let me ask another question, how ectjs can access to the packed files, if its possible so I can modify ectjs to get the files from .jx or .exe package.

**Comment by ktrzeciaknubisa** [comment]
The files are taken from the package transparently with `fs` module - no extra code required.

I guess in your case probably you need to alter ectjs module's code and disable the watch part for the views, because packaged files cannot be watched.

**Comment by fithwith** [comment]
how can I get the files with fs, can you provide me with an example?

**Comment by ktrzeciaknubisa** [comment]
It's documented here: [Accessing Files and Assets from a Package](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-feature-packaging-code-protection.markdown#accessing-files-and-assets-from-a-package) and it's no different that reading from file system.

```js
var fs = require('fs');

// gets index.html file from package's assets, if it does not exists on the disk.
var index = fs.readFileSync(__dirname + '/index.html');

// asset from subfolder:
var file = fs.readFileSync(__dirname + '/folder/file2.html');
```

**Comment by ktrzeciaknubisa** [comment]
One thought came to me: you may try to have an empty `/views` folder under package directory (real file system), while all the view files would reside inside a package. Maybe this would be enough to fool ectjs and not to throw an error on folder watch, while view files would still be accessible from a package?

**Comment by fithwith** [comment]
ok, I will try and keep you updated, thank you very much for your help and quick response :)

**Comment by fithwith** [comment]
1-having an empty folder is not working, we are getting the same error
2-when I checked the file ect.js at line 355 I found something like 
if(option.watch)
  startWatching bla bla bla  ;
so I discovered that there is an option named watch, then I changed ect initilisation to
var ectRenderer = ECT({ watch: false, root: __dirname + '/views', ext : '.ect' });
and now its working.

you can close the issue, thank you very much for your help :+1:

**Comment by ktrzeciaknubisa** [comment]
I'm glad we could find a solution :) Thanks!
