### ISSUE TITLE
unknown reason why 

### ISSUE THREAD

**Issue by ZeevM3** [jxcore/jxcore#473]
I have another issue with jxm.
code works fine when run through node.
I have no idea why its giving me this error now, i added alot of code and use these new modules:
    "connect-mongo": "^0.8.2",
    "request-ip": "^1.1.4"

fs.js:742
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\Users\zeev\Dropbox\Zeev\Projects\bin\node_modules'
    at Object.fs.lstatSync (fs.js:742:18)
    at Object.realpathSync (fs.js:1359:21)
    at tryFile (module.js:141:15)
    at tryExtensions (module.js:149:20)
    at Function.Module._findPath (module.js:194:18)
    at Function.Module._oldRes (module.js:679:25)
    at Function.Module._resolveFilename (module.js:1531:16)
    at Function.Module._load (module.js:291:25)
    at Module.require (module.js:388:17)
    at require (module.js:405:17)

**Comment by ZeevM3** [comment]
the problem is with express.io package

**Comment by ktrzeciaknubisa** [comment]
This happens on app startup?
Not sure what the folder `C:\Users\zeev\Dropbox\Zeev\Projects\bin\node_modules` is, but I assume that it exists, right?

**Comment by obastemur** [comment]
Please open `jxm` issues on it's own repository.
