### ISSUE TITLE
Native package on Windows is not able to require native addon from real file system

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#489]
**Platform:**
Windows 7 x64, JXcore 0.3.0.5 V8 / SM

**Scenario:** 
* creating a native package from jxcore-addon on Windows
* packing only **test.js**, nothing more. 
* leaving build/Release/binding.node intact on file system

This is a sample batch for the steps:

```bat
git clone https://github.com/jxcore/jxcore-addon
cd jxcore-addon
jx.exe install
jx.exe package test.js -add -native

test.exe
```

Now running **test.exe** (V8) exits silently at `require('./build/Release/binding')`. No error no exception. I've tried to try/catch but it doesn't help. Just the %errorlevel% is -1073741819 (0xc0000005, which is the code for STATUS_ACCESS_VIOLATION). 
This similar to https://github.com/jxcore/jxcore/issues/160#issuecomment-117790341.

SpiderMonkey **test.exe** at least displays an output:
```bash
Error: The specified procedure could not be found.
c:\jxcore\jxcore-issues\jxcore\_new\jxcore-addon\build\release\binding.node (native:jxcore_js_object 3:11)
    at  (native:jxcore_js_object:3:12)
    at process.dlopen (node.js:656:17)
    at Module.prototype.load (module.js:347:7)
    at Module._load (module.js:314:5)
    at Module.prototype.require (module.js:379:10)
    at require (module.js:397:12)
    at C:\jxcore\jxcore-issues\jxcore\_new\jxcore-addon\test.js.jx:8:17
    at Module.prototype._compile (module.js:520:10)
    at readX (module.js:12
```

I'm going to look at this.

**Comment by ktrzeciaknubisa** [comment]
**Update:** the addon gets loaded, but its execution fails at [node.cc#L1211](https://github.com/jxcore/jxcore/blob/master/src/node.cc#L121):

```c
 mod->register_func(exports, module);
```
This must be something related with `module` object passed from js side of native package.

If I run the test.js without a package, than it works as expected.
```bash
$ jx test.js
```
It also works for jx package:
```bash
jx.exe package test.js -add
jx.exe test.jx
```

**Comment by gitzalm** [comment]
Does it run if test.exe is renammed as jx.exe ?
I got a similar problem, resolved by renamming. A similar problem exists with nwjs : https://github.com/nwjs/nw.js/issues/199
A workaround is to rebuild jx from source to get a test.exe instead of jx.exe. Do not know if there is a simpler solution...
String "jx.exe" does exists in *.node file. Also replacing this string by a same length name works (eg aa.exe in *.node if final native is aa.exe)

**Comment by ktrzeciaknubisa** [comment]
@gitzalm Yes, you're right. After renaming *test.exe* to *jx.exe* it started to work.

I'm thinking... shall we implement internal binary string replacing (from *jx.exe* to *myapp.exe*) on native package creation for windows?

**Comment by obastemur** [comment]
> I'm thinking... shall we implement internal binary string replacing (from jx.exe to myapp.exe) on native package creation for windows?

We can not use a longer string than `jx.exe` so, eventually this will be a no go.

**Comment by ktrzeciaknubisa** [comment]
Even if we make the exe file few bytes bigger (shifting the tail) ? 
I mean, before:

###########jx.exe#########

and after:

###########myApp.exe#########

Never tried.

**Comment by WoLfulus** [comment]
Instead of binary string replacement (which might corrupt the executable), link all .node files against a common library (jxcore.dll for example) that will be used for both .exe and .node files, or just rebuild .node files, linking them against the final name before packaging.

**Comment by ktrzeciaknubisa** [comment]
> Instead of binary string replacement (which might corrupt the executable), link all .node files against a common library (jxcore.dll for example) 

Looks like node-webkit (which had the same problem) did something similar to what you say: https://github.com/nwjs/nw.js/issues/199#issuecomment-91411953

**Comment by ktrzeciaknubisa** [comment]
@gitzalm 

> A workaround is to rebuild jx from source to get a test.exe instead of jx.exe

That wasn't enough for me. My research shows that just having `jx.exe` rebuilt into `test.exe` is not important. However once you do that rebuild, you will also get `Release\test.lib` file and this is what we need here. It should be renamed into `~/.node-gyp/jxbxxx/ARCH/node.lib` (ARCH is e.g. x64). Then if you call `jx install` to rebuild _.node_ files of your app, they will be linked against string name "test.exe" (because `test.lib` - renamed to `node.lib` - references to it). That's how it worked for me.

This gives me some awkward idea: if we would provide multiple `node.lib` files under `~/.node-gyp/jxbxxx/` e.g. (`1.lib`, `12.lib`, `123.lib` etc. let's say up to 8) then we could instruct node-gyp to use one of them depending on user project name length. For "test" we would use `1234.lib` and then we can easily replace "1234" into "test" while packaging _.node_ files...

**Comment by nevf** [comment]
Sounds like progress is being made. Any thoughts on when we might get a resolution for this issue?
