### ISSUE TITLE
jx Windows x64: Error: %1 is not a valid Win32 application. 

### ISSUE THREAD

**Issue by nzhome** [jxcore/jxcore#515]
homebridge runs "node app.js"  but running the jx file has an error....

C:\Program Files\nodejs\node_modules>npm install homebridge
C:\Program Files\nodejs\node_modules>cd homebridge
C:\Program Files\nodejs\node_modules\homebridge>jx package app.js "HomeBridge"

Warning! ....erberos\build\Release\kerberos.node
Adding a .node (native) file into package may fail the application
Check the related discussion from https://github.com/jxcore/jxcore/issues/101
adding license LICENSE
adding readme README.md
[OK] compiled file is ready (HomeBridge.jx)

C:\Program Files\nodejs\node_modules\homebridge>jx HomeBridge.jx

C:\Program Files\nodejs\node_modules\homebridge\node_modules\mdns\lib\dns_sd.js.jx:34
    throw ex;
          ^
Error: %1 is not a valid Win32 application.
c:\program files\nodejs\node_modules\homebridge\node_modules\mdns\build\release\dns_sd_bindings.node
    at Object.process.dlopen [as .node] (node.js:676:25)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\homebridge\node_modules\mdns\lib\dns_sd.js.jx:23:20)
    at Module._compile (module.js:518:26)
    at Object.Module._extensions..jx (module.js:1653:7)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)

**Comment by obastemur** [comment]
As warning message shows, native dependencies brake packaging

**Comment by nzhome** [comment]
is there a flag that will skip native dependencies during the build? and will it work then? the app runs perfect on windows when I run node app.js currently.?

**Comment by ktrzeciaknubisa** [comment]
@nzhome Did you notice the following message in your output above?:

> Warning! ....erberos\build\Release\kerberos.node
Adding a .node (native) file into package may fail the application
Check the related discussion from #101 

To get rid of this warning, you may use partial extracting feature https://github.com/jxcore/jxcore/issues/370#issuecomment-131396697 introduced to JXcore 3.0.0.6, e.g.:

```bash
$ jx package app.js "HomeBridge" --extract-what "*.node" --extract-app-root
```

**Comment by nzhome** [comment]
thanks..  but that also did not work. I get a similar message now...


C:\Program Files\nodejs\node_modules\homebridge-milight-platform\node_modules\HAP-NodeJS\node_modules\mdns\lib\dns_sd.js.jx:34
    throw ex;
          ^
Error: %1 is not a valid Win32 application.
c:\program files\nodejs\node_modules\homebridge-milight-platform\node_modules\hap-nodejs\node_modules\mdns\build\release\dns_sd_bindings.node
    at Object.process.dlopen [as .node] (node.js:676:25)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\homebridge-milight-platform\node_modules\HAP-NodeJS\node_modules\mdns\lib\dns_sd.js.jx:23:20)
    at Module._compile (module.js:518:26)
    at Object.Module._extensions..jx (module.js:1653:7)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)

**Comment by nzhome** [comment]
running the app.js with directly with node runs all lib in homebridge just fine.. must be something with jxcore....  are there any other command line args that could help solve this? or can jxcore handle this automatically would be the ideal.

**Comment by ktrzeciaknubisa** [comment]
All right, but after all it looks like you don't even pack homebridge, right? It stays globally installed at `C:\Program Files\nodejs\node_modules\`?
