### ISSUE TITLE
gulp not working with sm engine

### ISSUE THREAD

**Issue by darrrk** [jxcore/jxcore#551]
```
TypeError: result.match(...) is null (/Users/darky/Desktop/tavmant/node_modules/gulp/node_modules/v8flags/index.js 63:16)
    at getFlags/< (/Users/darky/Desktop/tavmant/node_modules/gulp/node_modules/v8flags/index.js:63:17)
    at exithandler (child_process.js:663:7)
    at emit (events.js:85:7)
    at maybeClose (child_process.js:771:5)
    at ChildProcess.prototype.spawn/</< (child_process.js:994:11)
    at emit (events.js:82:7)
    at Socket.prototype._destroy/< (net.js:424:7)
```

**Comment by darrrk** [comment]
Maybe https://github.com/js-cli/js-v8flags/pull/26 fix this problem

**Comment by obastemur** [comment]
I saw this problem very recently too. @darrrk thanks for reporting. @ktrzeciaknubisa can you check this out ?

**Comment by ktrzeciaknubisa** [comment]
Gulp uses [v8flags](https://github.com/tkellen/node-v8flags) modules, which executes `jx --v8-options` and parses the result (this is to collect the list of v8-options). 

For SM we disabled this command and we display just `--v8-options are not available for non-V8 build`. The `match()` method here https://github.com/js-cli/js-v8flags/blob/master/index.js#L63 returns null, which causes the error. It looks like double space is needed in front of the output. 

The above commit adds it.
