### ISSUE TITLE
Can't install module on Android 4.4.2

### ISSUE THREAD

**Issue by 689** [jxcore/jxcore#628]
I tried to install express on rooted Samsung Galaxy Note 3; although jxcore did not complain, the module was not installed and 2 files were created under /.jx. Is there an option to turn on debug for jx install ?

```shell
root@hlte:/data # uname -a
Linux localhost 3.4.0-3031078 #1 SMP PREEMPT Fri Oct 17 18:30:51 KST 2014 armv7l GNU/Linux
root@hlte:/data # which jx
/system/xbin/jx
root@hlte:/data # ls -l /system/xbin/jx
lrwxrwxrwx root     root              2015-11-04 01:37 jx -> /data/jx
root@hlte:/data # jx -jxv
v 0.3.0.7
root@hlte:/data # jx -jsv
Google V8 v3.14.5.9
root@hlte:/data # env | grep HOME
HOME=/data
root@hlte:/data # cat jx.config
{
    "npmjxPath": "/data"
}
root@hlte:/data # jx install -g express
Preparing NPM for JXcore (v 0.3.0.7) for the first run
Make sure the user account has a write permission to it's home folder. >>
 Consider using a custom path from jx.config file's 'npmjxPath' property.
1|root@hlte:/data # mkdir .jx
root@hlte:/data # jx install -g express
Preparing NPM for JXcore (v 0.3.0.7) for the first run
127|root@hlte:
root@hlte:/data # ls -l .jx
-rw------- root     root       162934 2015-11-04 01:58 npmjxv1_9.jx
-rw------- root     root            1 2015-11-04 01:58 v 0.3.0.7
```

**Comment by obastemur** [comment]
This an npm issue. You need to install modules locally and then move to device

**Comment by ktrzeciaknubisa** [comment]
Or give up on `-g` switch. I remember that I was able to install npm packages on rooted android successfully without `-g`/`--global` option.

**Comment by ktrzeciaknubisa** [comment]
I repeated your steps to recheck my memory. Although I never had a problem with `Make sure the user account has a write permission to it's home folder` message, the installation of express succeeded once I got rid of `-g` switch.

```bash
shell@android:/data # pwd
/data
shell@android:/data # ./jx install express                                     
Preparing NPM for JXcore (v 0.3.0.7) for the first run
Downloading NPM for JXcore
..
NPM for JX is ready.
executing... please wait.
npm http GET https://registry.npmjs.org/express
...
express@4.13.3 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.1
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.3
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── etag@1.7.0
├── content-type@1.0.1
├── parseurl@1.3.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── qs@4.0.0
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)
```

**Comment by ktrzeciaknubisa** [comment]
BTW. I'm still looking at `-g` thing. I get an ugly exception when installing modules globally (rooted android). I wonder why @689 is not getting this?

```sh
TypeError: Cannot call method 'get' of undefined
    at /data/local/tmp/gluta/.jx/npm/lib/npm.js:312:23
    at /data/local/tmp/gluta/.jx/npm/node_modules/npmconf/npmconf.js:80:7
    at Array.forEach (native)
    at /data/local/tmp/gluta/.jx/npm/node_modules/npmconf/npmconf.js:79:13
    at f (/data/local/tmp/gluta/.jx/npm/node_modules/once/once.js:16:25)
    at /data/local/tmp/gluta/.jx/npm/node_modules/npmconf/npmconf.js:108:14
    at /data/local/tmp/gluta/.jx/npm/node_modules/uid-number/uid-number.js:53:14
    at ChildProcess.exithandler (child_process.js:663:7)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)


/data/local/tmp/gluta/.jx/npm/lib/npm.js:33
    throw new Error('npm.load() required')
Error: npm.load() required
    at Object.npm.config.get (/data/local/tmp/gluta/.jx/npm/lib/npm.js:33:11)
    at exit (/data/local/tmp/gluta/.jx/npm/lib/utils/error-handler.js:49:27)
    at process.errorHandler (/data/local/tmp/gluta/.jx/npm/lib/utils/error-handler.js:316:3)
    at process.emit (events.js:82:17)
    at process._fatalException (node.js:609:26)
7|shell@android:/data/local/tmp/gluta # 
```

So far I traced, that this is related with fetching uid/gid of `nobody` user:
```sh
[Error: setuid user id does not exist]
```

I'll be still looking.

**Comment by ktrzeciaknubisa** [comment]
All right, my exception was issued only when running `jx install -g module_name` **as root**. This can be avoided by adding `--unsafe-perm` flag. The above commit recognizes such case and displays proper warning:

> Global installation of modules on Android requires --unsafe-perm option.

**Comment by ktrzeciaknubisa** [comment]
Last thing to check here is to find out why @689 received

> Make sure the user account has a write permission to it's home folder. 

while permissions were granted.
