### ISSUE TITLE
jx install mongodb fails

### ISSUE THREAD

**Issue by milonas115** [jxcore/jxcore#652]
# jx install mongodb

make: Leaving directory `/milojs/node_modules/mongodb/node_modules/kerberos/build'
gyp ERR! build error
ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.jx/npm/node_modules/node-gyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:85:9)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:826:6)
gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
gyp ERR! command "jx" "/root/.jx/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /milojs/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok

**Comment by obastemur** [comment]
Using SM or v8 ?

**Comment by milonas115** [comment]
V8
