### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by jdonnerstag** [jxcore/jxcore#663]
Hi,

I tried jxcore with one of our apps. I create a (windows) executable, copied it into another folder and wanted to execute it. It seems as if src/util/logger.js is not able to require('./fc-configs') in the same directory. 

C:\Temp\murx>ghost.exe
module.js:776
throw err;
      ^
Error: Cannot find module './fc-configs'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1803:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (C:\Temp\murx\src\util\logger.js.jx:11:14)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..jx (module.js:1863:3)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)

**Comment by ktrzeciaknubisa** [comment]
Will it work, if you add the extension?

```js
require('./fc-configs.js');
```

**Comment by jdonnerstag** [comment]
add it where?  It is an existing node.js application that is in production and works fine.
the directory structure is like
./package.json
./src/util/logger.js
./src/util/fc-configs.js
very simple and straight forward

or do you mean to add the file extension like 
require('./fc-configs.js') rather than require('./fc.config') ??

**Comment by ktrzeciaknubisa** [comment]
> or do you mean to add the file extension like require('./fc-configs.js') rather than require('./fc.config') ??

Yeap, this is what i meant. Sorry for confusion :)

**Comment by ktrzeciaknubisa** [comment]
@jdonnerstag  I was packing a ghost solution recently (installed by `jx install ghost`) into exe and didn't meet the error you posted. How exactly did you prepare your ghost project, which got packed afterwards?
