### ISSUE TITLE
timeout with jx install jxm

### ISSUE THREAD

**Issue by mulderp** [jxcore/jxcore#667]
Hi,

I am trying to run:

    "c:\Program Files (x86)\jx_win64v8\jx.exe" install jxm

behind a corporate firewall with proxies enabled.

Yet,I get a response:

```
Preparing NPM for JXcore (v 0.3.0.7) for the first run

node.js:813
throw ee;
      ^
Error: connect ETIMEDOUT
    at errnoException (net.js:835:7)
    at Object.afterConnect [as oncomplete] (net.js:827:15)
```

**Comment by mulderp** [comment]
The packaging seems to run fine ,but I get a warning for packaging the serialport module:

```
Warning! ....node-v14-win32-ia32\serialport.node
Adding a .node (native) file into package may fail the application
Check the related discussion from https://github.com/jxcore/jxcore/issues/101
However you may mark .node files as extractable, e.g.: --extract-what '*.node'
..
[OK] compiled file is ready (C:\Users\account\nodejs\device\term.exe)
```

**Comment by ktrzeciaknubisa** [comment]
Hi. Is the timeout still occurring or it was just a temporary glitch?

***

The warning is for you. I says, that native addons (.node files) may not / will not work inside a native packages (.exe files), unless they will be e.g. extractable. See [partial extraction](http://jxcore.com/docs/jxcore-feature-packaging-code-protection.html#partial-extraction). Additionally on Windows, your package needs to be named jx.exe, so it can read addons properly: https://github.com/jxcore/jxcore/issues/489

**Comment by mulderp** [comment]
still timeout on: `c:\> jx install npm`

Win7, jxv 0.3.07, node v0.10.40

Any options to have verbose output turn on to see where it hangs?

**Comment by obastemur** [comment]
@ktrzeciaknubisa it's because @mulderp behind a proxy. AFAIK `jx install` supports setting proxy settings etc ?

**Comment by ktrzeciaknubisa** [comment]
@obastemur Yes, you're right proxy is supported by `jx install`. BTW. I think it may be improved to read npm's config files for proxy settings. 

@mulderp Please see our article [NPM package install through proxy with JXcore](http://jxcore.com/npm-package-install-through-proxy-with-jxcore/).

**Comment by obastemur** [comment]
@ktrzeciaknubisa lets create a Github issue and make this available after 0.3.1.0

**Comment by mulderp** [comment]
with `--https-proxy proxy.example.com:123` I get a:

```
Preparing NPM for JXcore (v 0.3.0.7) for the first run
{ [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall:
 'getaddrinfo' }
```

**Comment by ktrzeciaknubisa** [comment]
Try to add a protocol in front your of proxy url, e.g. `http://proxy.example.com:123`

**Comment by mulderp** [comment]
good point, that gives:

```
Preparing NPM for JXcore (v 0.3.0.7) for the first ru
{ [Error: socket hang up -2] code: 'ECONNRESET' }
```

**Comment by ktrzeciaknubisa** [comment]
Do you have npm installed? Is it working for you? If yes, what are the proxy settings, that you pass to npm (or you have defined in .npmrc ?)

**Comment by mulderp** [comment]
yes, npm works. I had to set npm config values as follows:

```
C:\Users\pm>npm config list
; cli configs
user-agent = "npm/2.9.1 node/v0.12.3 win32 ia32"

; userconfig C:\Users\pm\.npmrc
https-proxy = "http://proxy.example.com:123/"
proxy = "http://proxy.example.com:321/"
strict-ssl = false

; builtin config undefined
prefix = "C:\\Users\\pm\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files (x86)\nodejs\\node.exe
; cwd = C:\Users\pm
; HOME = C:\Users\pm
; 'npm config ls -l' to show all defaults.

```

**Comment by ktrzeciaknubisa** [comment]
Ok, you may try to add `--proxy` as well:

```bash
> jx.exe install jxm --https-proxy http://proxy.example.com:123 --proxy http://proxy.example.com:321
```

**Comment by mulderp** [comment]
hmm.. it gives again the socket hang up. Possibly it is something with the http-proxy module, googling resulted into https://github.com/nodejitsu/node-http-proxy/issues/184  - but not sure if it may help.

**Comment by ktrzeciaknubisa** [comment]
Ok. Let's try another way. This is excerpt from `jx install` proxy usage: [test.js](https://github.com/ktrzeciaknubisa/jxcore-issues/blob/master/jxcore/x667/test.js). If you could play with it a little and make it work on your platform, then we would know what's wrong.

You may run it with:

```bash
> jx.exe test.js --https-proxy http://proxy.example.com:123 --proxy http://proxy.example.com:321
```

My guessing is, that either one or two of the following should be added to `opts` in [test.js#L22-L30](https://github.com/ktrzeciaknubisa/jxcore-issues/blob/master/jxcore/x667/test.js#L22-L30):

1. add `user-agents` to `headers`
2. and / or add `rejectUnauthorized` (that's what your `strict-ssl` setting does)
    
For example:

```js
  var opts = {
    host: parsed_proxy_url.hostname,
    port: parsed_proxy_url.port,
    method: 'CONNECT',
    path: parsed_url.hostname,
    headers: {
      Host: parsed_url.hostname,
      // HERE
      "user-agent" : "npm/2.9.1 node/v0.12.3 win32 ia32"
    }
    // HERE
    rejectUnauthorized : false
  };
```

I'm not sure if same should be added [few lines below](https://github.com/ktrzeciaknubisa/jxcore-issues/blob/master/jxcore/x667/test.js#L38-L41) or not, but you may try it as well if above will not help.

**Comment by mulderp** [comment]
no difference, "socket hangs up", possibly it has to do with the user agent: http://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean ?

**Comment by mulderp** [comment]
the relevant discussion in npmjs might be https://github.com/npm/npm/issues/6007

**Comment by ktrzeciaknubisa** [comment]
Those problems seems not to be related with npm. At this step npm is not even called yet. 

So the thing basically comes down to make a working code, which would fetch any file through your proxy by using node's core `http`/`https` modules (like above test.js) and without any other 3rd party node modules. Maybe you have such sample in other projects, that works on your platform?

Without access to such environment for testing I'm out of ideas right now.

**Comment by mulderp** [comment]
I am guessing the problem might be cause that proxy is looking for certain values in the HTTP header, e.g user agent. This week will be hard to check this idea, but possibly a proxy server for testing that dumps a HTTP headers (to compare difference between npm and jxm) might be interesting. I'll check next week for this.

**Comment by ktrzeciaknubisa** [comment]
Well, not really sure if that matters, but you may also try uppercase `User-Agent`. At least in [docs](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) it's mentioned that way.

**Comment by ktrzeciaknubisa** [comment]
Closing this due to no activity. There is also new npm 3.3.12 added to JXcore 0.3.1.1 so it is worth to re-try the scenario. @mulderp Please let us know if if you still have any issues.

**Comment by Srividya2212** [comment]
This link is broken : NPM package install through proxy with JXcore

**Comment by Kurara** [comment]
One year later and still we have this problem. How can we solve it? As @Srividya2212  says the link is broken.

**Comment by yaronyg** [comment]
@Kurara There is no one officially supporting JXcore anymore. So if you want something fixed you have to do it yourself.
