### ISSUE TITLE
SM + V8: typeof jxcore.uwp error

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#735]
Is this intended?

```bash
$ jx -e "console.log(typeof jxcore.uwp);"

_jx_loadEmbedded.js:11
mod.loadInternal(cc,name);
    ^
Error: Requested native module wasn't embedded.
    at Object.exports.require (_jx_loadEmbedded.js:11:5)
    at Object.uwp (node.js:639:49)
    at [eval]:1:26
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:619:24)
    at evalScript (node.js:1038:19)
    at startup (node.js:403:1)
    at node.js:1588:1
```

**Comment by obastemur** [comment]
We could show more friendly message. Yes at the moment it is only available with Chakra build

**Comment by obastemur** [comment]
@karaxuna we might throw a friendly error here?

**Comment by karaxuna** [comment]
@obastemur  "Requested native module uwp wasn't embedded. It's only available with Chakra build." will be ok?

**Comment by obastemur** [comment]
"Not Implemented: jxcore.uwp feature is limited to Chakra builds" ?
