### ISSUE TITLE
 Failed at the epoll@0.1.16 install script.

### ISSUE THREAD

**Issue by yaseenox** [jxcore/jxcore#743]
I want to control gpio pins of raspberry pi running openwrt chaos calmer using node.js scripts. When I try to install epoll package which is a dependency for gpio control packages I get error. Here is the message:

root@OpenWrt:/jxnode-for-openwrt# jx install epoll
npm http GET https://registry.npmjs.org/epoll
npm http 304 https://registry.npmjs.org/epoll
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
 
> epoll@0.1.16 install /jxnode-for-openwrt/node_modules/epoll
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack     at exithandler@child_process.js:665:15
gyp ERR! stack     at emit@events.js:85:9
 ERR! stack     at maybeClose@child_process.js:773:5
 ERR! stack     at ChildProcess.prototype.spawn/</<@child_process.js:994:11
ERR! stack     at emit@events.js:82:9
ERR! stack     at Socket.prototype._destroy/<@net.js:422:7
gyp ERR! System Linux 3.18.20
 ERR! command "jx" "/root/.jx/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
 ERR! cwd /jxnode-for-openwrt/node_modules/epoll
 ERR! node -v v0.10.40
ERR! node-gyp -v v0.13.1
ERR! not ok 
npm ERR! epoll@0.1.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the epoll@0.1.16 install script.
npm ERR! This is most likely a problem with the epoll package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls epoll
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.18.20
npm ERR! command "/bin/jx" "/root/.jx/npm" "install" "--loglevel" "http" "--color" "true" "epoll" "--build-from-source"
npm ERR! cwd /jxnode-for-openwrt
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /jxnode-for-openwrt/npm-debug.log
npm ERR! not ok code 0
--------------------------------------------------------------
How to fix this problem or another way to control gpio pins.
Thanks :)

**Comment by ktrzeciaknubisa** [comment]
Hi @yaseenox . Installing npm modules on OpenWRT is a tricky subject. Please, see if the discussion https://github.com/jxcore/jxcore/issues/648 helps you.

**Comment by yaseenox** [comment]
Hi Krzysztof, 
So I can install the modules on my pc and move them to the openwork device. Thank you that was very helpful.

**Comment by ktrzeciaknubisa** [comment]
You're welcome @yaseenox . I think this approach is best for all npm modules, except the ones which use native addons (*.node* files which get compiled on module's install). Look's like epoll **is** using native addons, so I'm not sure whether this will work when you copy into the OpenWRT after all.

**Comment by ktrzeciaknubisa** [comment]
You're welcome @yaseenox . I think this approach is best for all npm modules, except the ones which use native addons (*.node* files which get compiled on module's install). Look's like epoll **is** using native addons, so I'm not sure whether this will work when you copy into the OpenWRT after all.

**Comment by yaseenox** [comment]
You are right it didn’t work. Can you give me a direction and I will do some googling actually I am new to the hole embedded systems domain and I chose openwork for my project.
I appreciate your help :)

yaseen

**Comment by obastemur** [comment]
@yaseenox node.js native module mostly means a module is developed using (C, C++). In order to run a C,C++ solution on OpenWRT platform you should cross compile it as we cross compile JXcore. 

We might embed some of these modules into JXcore's build optionally since they are useful for IoT targets.
