### ISSUE TITLE
require.resolve() appends '.jx' postfix to asset files

### ISSUE THREAD

**Issue by vu-bui** [jxcore/jxcore#765]
I'm using JXCore to bundle my application to a single executable file, and there is a problem with `exceljs` module when running the bundle. The module seems to use `require.resolve()` to get the absolute location of its supporting xml files before loading it. Everything is fine until I bundle everything and start getting this error:
```
Unhandled rejection Error: ENOENT, open '/Users/vubui/development/test-exceljs/node_modules/exceljs/lib/xlsx/content-types.xml.jx'
    at Error (native)
```
I figured out a workaround by adding `--extract --extract-app-root --extract-what "node_modules/exceljs/lib/xlsx/**.xml,node_modules/exceljs/lib/xlsx/.rels"` to the package command, but then, the application can only be executed in the directory that contains it. Trying to run the file from the outside causes this error:
```
➜  test-exceljs  ./dist/index 

module.js:802
throw err;
      ^
Error: Cannot find module './content-types.xml'
    at Function.Module._oldRes (module.js:800:9)
    at Function.Module._resolveFilename (module.js:1850:15)
    at Function.require.resolve (module.js:497:15)
    at Object.XLSX.addContentTypes (/Users/vubui/development/test-exceljs/dist/node_modules/exceljs/lib/xlsx/xlsx.js.jx:887:44)
    at Object.XLSX.write (/Users/vubui/development/test-exceljs/dist/node_modules/exceljs/lib/xlsx/xlsx.js.jx:1204:18)
    at Object.XLSX.writeFile (/Users/vubui/development/test-exceljs/dist/node_modules/exceljs/lib/xlsx/xlsx.js.jx:1242:14)
    at Object.<anonymous> (/Users/vubui/development/test-exceljs/dist/index.js.jx:11:15)
    at Module._compile (module.js:619:24)
    at readX (module.js:1535:3)
    at Object.Module._extensions..jx (module.js:1987:8)
    at Module.load (module.js:440:30)
    at Function.Module._load (module.js:405:8)
    at Module.require (module.js:475:15)
    at require (module.js:493:13)
    at Object.<anonymous> (_jx_source:17:1)
    at Module._compile (module.js:619:24)
```
Here is my code snippet:
```javascript
var Excel = require("exceljs");

var workbook = new Excel.Workbook();
workbook.creator = "Me";
workbook.lastModifiedBy = "Her";
workbook.created = new Date(1985, 8, 30);
workbook.modified = new Date();

workbook.addWorksheet("My Sheet");

workbook.xlsx.writeFile("test.xlsx");
```
And here is the line in the library that causes the error:
```javascript
return utils.fetchTemplate(require.resolve("./content-types.xml"))
```

**Comment by vu-bui** [comment]
It seems that the `--extract-app-root` option always extracts the files to the current directory (not the directory that contains the executable), but the `require.resolve()` returns the path relative to the file calling it.

**Comment by ktrzeciaknubisa** [comment]
> but then, the application can only be executed in the directory that contains it. 

Yes, packages should be executed from their folder location (no matter if they are extractable or not).

I reproduce your initial `Unhandled rejection Error: ENOENT` error (however first I needed to apply a fix to `exceljs` https://github.com/guyonroche/exceljs/issues/53, otherwise It would stop on `ReferenceError: err is not defined`). 

Looks like previous jx 0.3.0.7 also suffers the issue.

**Comment by ktrzeciaknubisa** [comment]
Generally adding `.jx` postfix for packaged files/assets is part of the design, however as we may see at [module.js#L502](https://github.com/jxcore/jxcore/blob/0.3.1.1/lib/module.js#L502) `require.resolve()` returns the path without this postfix, but **only** for .js files. 

```js
      if (fn.toLowerCase().indexOf('.js.jx') == fn.length - 6)
        fn = fn.substr(0, fn.length - 3);
```

I'm not sure If we can force stripping the postfix for all files without any side effects? @obastemur ?
