### ISSUE TITLE
JXCore configuration for no Cordova Projects

### ISSUE THREAD

**Issue by carlgira** [jxcore/jxcore#768]
Hi

There is a tutorial, or updated example that can be followed to add Jxcore to a android project that does not use cordova??

The only thing I was able to find was an example on github about 6 months ago https://github.com/capriza/jxcore-android-sample

The problem is that I was getting an error with that example because a bug you already have solved with the cordova-jxcore plugin..... so I begin to update that sample merging  the cordova plugin sources with the ones in the project. I was able to make it work but in the process i had to erase all the cordova stuff and i'm not sure if I do it right.

The only file that i had to manually change was the jxcore.java. I put all the changes

1. Remove the references of Cordova (imports and the "extends CordovaPlugin")
2. Remove the fields
    Map callbacks;
    PluginResult result_;
3. Remove the functions
    CreateResult
    jx_callback
    execute
4. Change the functions onStart and onStop to remove the parameter "boolean multitasking"
5. Change the function pluginInitialize.
    Remove the "@Override"
    Remove activity reference
    Remove the callbacks Map initialization
    Remove the RegisterMethod call
    Make it public so it can be called from outside to initialize the class.
6. Add a constructor to pass the "activity"

I add some other little changes and update the .so files

You can see the sources of this on github. I create a jxcore-android lib and an android application sample to execute it.
https://github.com/carlgira/jxcore

Is there something that i should not delete on jxcore.java?

Thanks!
Carlos Giraldo

**Comment by obastemur** [comment]
> Is there something that i should not delete on jxcore.java?

It depends what do you want to do. Did you also cleanup the JS file ?

**Comment by carlgira** [comment]
I copy and paste the jxcore_cordova.js (no changes) and it work perfectly. (No log errors, or problem executing modules, or problem registering methods)

I manualy check the file but i could not see any specific reference to cordova, so i let it like that.

The only file i change was jxcore.java.

**Comment by obastemur** [comment]
It should not work as is. So how you are able to load your JS file ?

**Comment by carlgira** [comment]
Sorry, what i wanted to say was that i didn't need to erase anything from the jxcore_cordoda.js, but i indeed add some code to load my js. (a "require" of my js  and some init functions)

**Comment by obastemur** [comment]
@carlgira So you have it working or is there a problem?

**Comment by carlgira** [comment]
It's working, i just wanted to know one thing.

After the list of changes i did to make the example work with no cordova (in the first message are all the changes) is there something i should not delete?

**Comment by JarshChen** [comment]
Hi @carlgira @obastemur 
Did you encounter problem when generating release signed apk?
I can run the sample project https://github.com/capriza/jxcore-android-sample with debug key.
But when generating release signed apk, encounters  Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0

01-12 19:53:31.951 20846-21228/? D/jxcore_app_log: JniHelper::setJavaVM(0xb489d200), pthread_self() = -1265512320
01-12 19:53:31.951 20846-21228/? D/jxcore: jxcore constructor called
01-12 19:53:31.952 20846-21228/? D/jxcore: jxcore initialized with taskOptions: {"fileName":"someFile.json"} home: /data/user/0/com.android.jxcore.jxcoresample/files
01-12 19:53:31.952 20846-21228/? D/jxcore: JXCore Java thread id: 1580
01-12 19:53:31.957 357-827/? D/audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
01-12 19:53:31.957 357-827/? D/msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
01-12 19:53:31.957 357-827/? E/ACDB-LOADER: Error: ACDB AFE returned = -19
01-12 19:53:31.957 357-827/? D/audio_hw_primary: enable_snd_device: snd_device(2: speaker)
01-12 19:53:31.959 357-827/? D/audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback speaker
01-12 19:53:31.959 20846-21228/? D/jxcore-ndk: prepareEngineOri called thread id: -1265512320 isAlive is: 0
01-12 19:53:31.959 20846-21228/? D/jxcore-ndk: Initializing engine capriza
01-12 19:53:31.960 20846-21228/? W/jxcore-log: Initializing JXcore engine
01-12 19:53:31.960 20846-21228/? W/jxcore-log: JXcore engine is ready
01-12 19:53:31.960 20846-21228/? D/jxcore-ndk: prepareEngineOri ended spidermonkey?: 1 v8?: 0
01-12 19:53:31.965 20846-21228/? D/jxcore-ndk: defineMainFile started
01-12 19:53:31.965 20846-21228/? D/jxcore-ndk: defineMainFile ended
01-12 19:53:31.965 20846-21228/? D/jxcore-ndk: startEngine called thread id: -1265512320
01-12 19:53:31.965 20846-21228/? W/jxcore-log: Starting JXcore engine
01-12 19:53:31.997 21228-21228/? W/com.android.jxcore.jxcoresample: type=1400 audit(0.0:323): avc: denied { ioctl } for comm=4173796E635461736B202331 path="socket:[13066]" dev="sockfs" ino=13066 scontext=u:r:untrusted_app:s0 tcontext=u:r:zygote:s0 tclass=unix_dgram_socket permissive=0
01-12 19:53:31.997 21228-21228/? W/com.android.jxcore.jxcoresample: type=1400 audit(0.0:324): avc: denied { ioctl } for comm=4173796E635461736B202331 path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=4163 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=0
01-12 19:53:31.997 21228-21228/? W/com.android.jxcore.jxcoresample: type=1400 audit(0.0:325): avc: denied { ioctl } for comm=4173796E635461736B202331 path="socket:[9640]" dev="sockfs" ino=9640 scontext=u:r:untrusted_app:s0 tcontext=u:r:zygote:s0 tclass=unix_dgram_socket permissive=0
01-12 19:53:31.997 21228-21228/? W/com.android.jxcore.jxcoresample: type=1400 audit(0.0:326): avc: denied { ioctl } for comm=4173796E635461736B202331 path="socket:[136204]" dev="sockfs" ino=136204 scontext=u:r:untrusted_app:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
01-12 19:53:32.051 20846-21228/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 21228 (AsyncTask #1)

**Comment by obastemur** [comment]
@carlgira @JarshChen looks like I should be working on a standalone solution with latest.

**Comment by JarshChen** [comment]
Hi @obastemur 
I got the upper error when I set android:debuggable="false" manually in AndroidManifest.xml.
Is it a known issue?

**Comment by obastemur** [comment]
No, such issue is not available for jxcore or jxcore-cordova. I'm gonna spend some time on cordova free jxcore android project.

**Comment by JarshChen** [comment]
I am appreciated with your working and looking forward to your update. 
Have you known the possible cause now?

**Comment by SyRenity** [comment]
Just wanted to mention the example at https://github.com/carlgira/jxcore solved same bad issues we had with setInterval and setTimeout calls, will be great to have the signed APK issue solved.

Also really worth adding to Wiki for future users.

**Comment by JarshChen** [comment]
@SyRenity 
Thank you for the information.
@carlgira 
I test your project. This project does not have release signed issue and works on android 6.0 as well.
I appreciate your great work :).
However, may I know what is your jxcore library version? 
I used v0.3.1.0 on this project but got a crash on x86 ASUS ZenPhone2 device.
If I changed the jxcore libraries to v0.3.0.7, no obvious issue was found so far.
Did you encounter the same issue?
Thank you!

**Comment by carlgira** [comment]
@JarshChen 
I use the last libraries available with the jxcore cordova plugin v 0.3.1.0 i haven't found any problem.

Not related with the subject, but, i just finish to create an example with IOS. There is a framework library and application example. (The framework allows to more easily  add jxcore to other projects)

I put some instructions explaining everything  https://github.com/carlgira/jxcore-ios

**Comment by JarshChen** [comment]
@carlgira @obastemur 

I got an error on several specific devices: 
URBANO V01 (4.4.4)  
INFOBAR A03 (4.4.4) 
AQUOS SERIE mini SHV31 (4.4.4)

all OS version is 4.4.4 , but not every 4.4.4 device will encounter this issue.

How to reproduce it? Just create a http server and listen on arbitrary port.

Have any suggestion?

03-01 23:13:49.649 17555 17555 I jxcore-log: JXCoreModule_startServer method
03-01 23:13:49.649 17555 17555 I jxcore-log: 
03-01 23:13:49.649 17555 17555 I jxcore  : Callback, ServerStarted! 
03-01 23:13:49.659 17555 17555 E jxcore  : Error!: listen EFAULT
03-01 23:13:49.659 17555 17555 E jxcore  : Stack: [{"_fileName":"net.js","_functionName":"errnoException","_lineNumber":"835","_columnNumber":"11","_msg":"    at errnoException@net.js:835:11"},{"_fileName":"net.js","_functionName":"Server.prototype._listen2","_lineNumber":"974","_columnNumber":"14","_msg":"    at Server.prototype._listen2@net.js:974:14"},{"_fileName":"net.js","_functionName":"listen","_lineNumber":"995","_columnNumber":"5","_msg":"    at listen@net.js:995:5"},{"_fileName":"net.js","_functionName":"Server.prototype.listen","_lineNumber":"1068","_columnNumber":"5","_msg":"    at Server.prototype.listen@net.js:1068:5"},{"_fileName":"/data/data/carlgira.com.android_jxcore_sample/files/www/jxcore/ws_server.js","_functionName":"WSLocalServer.startServer","_lineNumber":"47","_columnNumber":"7","_msg":"    at WSLocalServer.startServer@/data/data/carlgira.com.android_jxcore_sample/files/www/jxcore/ws_server.js:47:7"},{"_fileName":"/data/data/carlgira.com.android_jxcore_sample/files/www/jxcore/jxcore_module.js","_functionName":"JXCoreModule.registerJSFunction/startServerFunction<","_lineNumber":"15","_columnNumber":"13","_msg":"    at JXCoreModule.registerJSFunction/startServerFunction<@/data/data/carlgira.com.android_jxcore_sample/files/www/jxcore/jxcore_module.js:15:13"},{"_fileName":"main.js","_functionName":"JXMobile.ping","_lineNumber":"93","_columnNumber":"14","_msg":"    at JXMobile.ping@main.js:93:14"},{"_fileName":"net.js","_functionName":"unknown","_lineNumber":835,"_columnNumber":10,"_msg":"    at "}]

Thank you.
