### ISSUE TITLE
loopback won't run with jxcore

### ISSUE THREAD

**Issue by johannesjo** [jxcore/jxcore#804]
In my production environment (Plesk running JXCore and node v.0.10.24) I get the following error on every request that requires authentication. Locally everything works fine.

I really would be thankful for any clue about what could be causing this.
```
/my-project/node_modules/loopback/node_modules/continuation-local-storage/context.js:78
throw exception;
^
TypeError: Cannot read property 'length' of undefined
at IncomingMessage.removeListener (events.js:181:16)
at IncomingMessage.removed (/my-project/node_modules/loopback/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:106:35)
at cleanup (/my-project/node_modules/loopback/node_modules/body-parser/node_modules/raw-body/index.js:317:12)
at invokeCallback (/my-project/node_modules/loopback/node_modules/body-parser/node_modules/raw-body/index.js:255:7)
at done (/my-project/node_modules/loopback/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
at IncomingMessage.onEnd (/my-project/node_modules/loopback/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
at IncomingMessage. (/my-project/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17)
at IncomingMessage.emit (events.js:79:17)
at IncomingMessage.emitted [as emit] (/my-project/node_modules/loopback/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:122:21)
at _stream_readable.js:889:16
Spawner error:  Application exited by itself with code: 8
Spawner info:   Spawner could not kill the app when exiting: Error: kill ESRCH
Spawner info:   Subscribing is delayed by 2000 ms.
Spawner info:   Subscribed successfully (as root): Successfully subscribed process 32307 to the monitor.
Spawner info:   Restart manager is active.
Web server listening at: http://0.0.0.0:10014
Browse your REST API at http://0.0.0.0:10014/explorer
```

**Comment by ktrzeciaknubisa** [comment]
> Locally everything works fine.

Do you mean on your dev machine it runs with jx (from the command line). So it doesn't work on production env under Plesk? How about production env + command line ?

**Comment by johannesjo** [comment]
No it runs just with a regular node installation. I'm aware that this might not be related to jxcore, but the error message and stacktrace are not too helpful and I don't know where to start.

**Comment by ktrzeciaknubisa** [comment]
How can we reproduce this? Are you able to share a minimal sample?

**Comment by johannesjo** [comment]
A basic application loopback created by the `slc loopback` command should do.

You could use this example for example: https://github.com/strongloop/loopback-example-angular

**Comment by ktrzeciaknubisa** [comment]
I was able to reproduce the problem. I'm going to look for a reason.

**Comment by ktrzeciaknubisa** [comment]
The above commit solves the issue. @johannesjo the fix will come with next jxcore release. If you can't wait or build JXcore by yourself, you may modify `node_modules/emitter-listener/listener.js` and add `catch` in `remover()` method as follows:

```diff
diff --git a/listener.js b/listener.js
index 0f836be..07a1b45 100644
--- a/listener.js
+++ b/listener.js
@@ -105,6 +105,7 @@ module.exports = function wrapEmitter(emitter, onAddListener, onEmit) {
           try {
             return removeListener.apply(this, arguments);
           }
+          catch (ex) {}
           finally {
             unwrapped = this._events[event];
             this._events[event] = _wrap(unwrapped, onEmit);
```

**Comment by johannesjo** [comment]
@thank you very much. I'll check it out.
