### ISSUE TITLE
Issue with node sass

### ISSUE THREAD

**Issue by johannesjo** [jxcore/jxcore#820]
Using node v5.5.0 and npm 3.3.12 I'm getting the following error message for node-sass:
```
Spawner info:	Log file cleared.
Unhandled rejection Error: The `libsass` binding was not found in /my-project/node_modules/node-sass/vendor/linux-x64-11/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
at Object.sass.getBinaryPath (/my-project/node_modules/node-sass/lib/extensions.js:158:11)
at Object. (/my-project/node_modules/node-sass/lib/index.js:16:36)
at Module._compile (module.js:619:26)
at Object.Module._extensions..js (module.js:649:10)
at Module.load (module.js:440:36)
at Function.Module._load (module.js:405:12)
at Module.require (module.js:475:17)
at require (module.js:493:17)
at renderSass (/my-project/node_modules/email-templates/lib/template-manager.js:113:14)
at /my-project/node_modules/email-templates/lib/template-manager.js:63:22
at Promise._execute (/my-project/node_modules/bluebird/js/release/debuggability.js:180:9)
at Promise._resolveFromExecutor (/my-project/node_modules/bluebird/js/release/promise.js:462:18)
at new Promise (/my-project/node_modules/bluebird/js/release/promise.js:77:14)
at render (/my-project/node_modules/email-templates/lib/template-manager.js:45:10)
at renderFile (/my-project/node_modules/email-templates/lib/util.js:53:38)
at /my-project/node_modules/email-templates/lib/email-template.js:172:30
at Promise._execute (/my-project/node_modules/bluebird/js/release/debuggability.js:180:9)
at Promise._resolveFromExecutor (/my-project/node_modules/bluebird/js/release/promise.js:462:18)
at new Promise (/my-project/node_modules/bluebird/js/release/promise.js:77:14)
at EmailTemplate._renderStyle (/my-project/node_modules/email-templates/lib/email-template.js:164:14)
at /my-project/node_modules/email-templates/lib/email-template.js:123:97
at tryCatcher (/my-project/node_modules/bluebird/js/release/util.js:11:23)
```

**Comment by ktrzeciaknubisa** [comment]
@johannesjo You've mentioned node version, but does it have anything to do here? Did you install node-sass with `jx install` ?
