### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by giulianozorzi** [jxcore/jxcore#867]
Hi, it seems that Promise() is not supported  on latest jxcore. Is there any plan to support it ?

thanks

giuliano

**Comment by giulianozorzi** [comment]
sample code:

app.js:

function test() {
	return new Promise(function(success,fail) {
		success('ok');
	});
}

test().then(
	function(res) { 
		console.log(res); 
	}
);


running under node 4.4 returns "oK"

running under jx (after jx package app.js)

/home/giuliano/node/promise/app.js.jx:2
        return new Promise(function(success,fail) {
                   ^
ReferenceError: Promise is not defined
    at test (/home/giuliano/node/promise/app.js.jx:2:13)
    at Object.<anonymous> (/home/giuliano/node/promise/app.js.jx:7:1)
    at Module._compile (module.js:595:24)
    at readX (module.js:1488:3)
    at Object.Module._extensions..jx (module.js:1921:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)
    at Function.Module.runMain (module.js:816:8)
    at startup (node.js:374:8)
    at node.js:1461:1


versions:

node --version
v4.4.0

jx --version
v0.10.40

 uname -a
Linux localhost.localdomain 4.4.3-201.fc22.x86_64 #1 SMP Sat Feb 27 11:53:28 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lopezdonaque** [comment]
+1!!

**Comment by voxsoftware** [comment]
You can use bluebird for support Promise. Maybe you can use vox-core to support ES6 Syntax
