### ISSUE TITLE
jx install fails: Sites unreachable?

### ISSUE THREAD

**Issue by lamuertepeluda** [jxcore/jxcore#874]
I'm facing troubles with
`jx install express`(or any other jx install with latest 0.3.1.1 binaries)

on mac osx (trying to add modules for android)

```bash
jx install express
Preparing NPM for JXcore (v0.3.1.1) for the first run
Your package was created with older JXcore packaging format which is currently depreciated and its support will be removed in future JXcore releases.
Don`t worry, for the moment the package can still be executed.
However we recommend recreating a package using the latest JXcore version (also for better performance).

module.js:2098
    throw err;
          ^
Error: Package is either corrupted or not compatible with this JX binary. (/Users/vitomacchia/.jx/npmjxv311.jx)
    at Object.Module._extensions..jx (module.js:2095:15)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:878:12)
    at startup (node.js:485:18)
    at node.js:1604:3
````

Tried:
```bash
cat /Users/vitomacchia/.jx/npmjxv311.jx                                                                                                               8 ↵
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>2E70711E2AECD005</RequestId><HostId>rRMJGPNrndrlzWOVm1yF/HuOnFOb+BT34gtrUL0wMVC/g/G8vQwqIYVCKv5SC7sfmIYXd94VDLU=</HostId></Error>%
```

By the way, jxcore.io is unreachable and https://s3.amazonaws.com/nodejx/npmjxv311.jx is returning the same xml above

Are you perhaps having issues with amazon? Is this a consequence of halting actived development etc?

**Comment by cicorias** [comment]
FYI - [ThaliProject](https://github.com/thaliproject) is hosting SOME of the binaries based upon private builds that incorporate some changes - not many.  1 specific change is updating the endpoints for where binaries are..

Note that NOT all binaries are hosted. 

And we cannot manage the work, but again, Pull Requests are accepted...

**Comment by lamuertepeluda** [comment]
@cicorias Thank you! At least now, after compiling your version of jxcore for OSX, `jx install` is working as expected.

I'm still having troubles with jade with android + express (tried `npm install jade` --> runtime errors when rendering, then now with `jx install` same runtime errors on **android only**, while works fine on osx).
I'll try to update jxcore-cordva binaries with your version too before giving up with jade :disappointed:

**Comment by lamuertepeluda** [comment]
Still cannot run jade... pity:

```
04-01 18:06:29.713: E/jxcore-log(10964): DEBUG: ERROR in file: /data/data/it.ismb.JXCoreTest/files/www/jxcore/node_modules/transformers/node_modules/uglify-js/lib/parse.js / Error: Uncaught exception at /data/data/it.ismb.JXCoreTest/files/www/jxcore/node_modules/transformers/node_modules/uglify-js/lib/parse.js
04-01 18:06:29.713: E/jxcore-log(10964): 	words.split is not a function
```

I have no idea on what could be the problem here... I think I will leave jade and run express without template engine :sob:

**Comment by cicorias** [comment]
Please IGNORE this PR - as it's incorrect.

**Comment by nevf** [comment]
@cicorias I've just come back to jxcore and am running in circles - I had no idea jxcore had been killed off - a great project and huge dissapointment. 

Anyway I'm having the same problem as @lamuertepeluda I've looked at your Github repos and can't see any jx binaries? Any help appreciated. Are you binaries using a recent version of Node?

**Comment by yecapee** [comment]
How to change updating  endpoints? 
I have similar problems

run jx npm init faild
