### ISSUE TITLE
nodejx.s3.amazonaws.com not longer available?

### ISSUE THREAD

**Issue by medemi68** [jxcore/jxcore#882]
http://nodejx.s3.amazonaws.com/jxb311.tar.gz

Tying to install deasync using jx install. I've installed node-gyp, i'm on the required version of python. And now, It needs this.

**Comment by murphy85** [comment]
Me too... But there are some more issues. I tried to followed Mac instructions on https://github.com/jxcore/jxcore-release and https://github.com/jxcore/jxcore/blob/master/doc/INSTALLATION.md but nothing worked.

http://jxcore.com/xil.sh -> 404 not found
https://jxcore.s3.amazonaws.com/latest.txt -> Error, NoSuchBucket
http://www.jxcore.io/ -> URL not found

Then I cloned git and started configure and make. Another issue...

> Preparing NPM for JXcore (v0.3.1.2) for the first run
> Your package was created with older JXcore packaging format which is currently depreciated and its support will be removed in future JXcore releases.
> Don`t worry, for the moment the package can still be executed.
> However we recommend recreating a package using the latest JXcore version (also for better performance).
> 
> module.js:2098
>     throw err;
>           ^
> Error: Package is either corrupted or not compatible with this JX binary. (/Users/alex/.jx/npmjxv311.jx)
>     at Object.Module._extensions..jx (module.js:2095:15)
>     at Module.load (module.js:440:36)
>     at Function.Module._load (module.js:405:12)
>     at Function.Module.runMain (module.js:878:12)
>     at startup (node.js:485:18)
>     at node.js:1604:3

That's a little bit disappointing :-(

**Comment by yaronyg** [comment]
https://github.com/thaliproject/jxbuild is where we record our instructions for building the variants of JXcore we use (including on OS/X). It also includes links to our binaries. You are free to use those binaries but please keep in mind that we have absolutely no guarantee for availability, up-to-date'edness, etc. So you are on your own.

**Comment by murphy85** [comment]
Thank you for your response! I will try that tomorrow. Maybe there is
another problem with our corporate proxy settings.

Best regards,
Alexander Bering
Am 10.05.2016 20:54 schrieb "Yaron Y Goland" <notifications@github.com>:

**Comment by jasonkarns** [comment]
Any chance that @obastemur or @ktrzeciaknubisa might be able to share the prebuilt binaries (and npmjx packages) from previous versions? If these binaries already exist somewhere and could be shared, I would be more than happy to help get them uploaded to github as release artifacts.

**Comment by jasonkarns** [comment]
Any luck @yaronyg @murphy85 finding old binaries? I have a list of checksums for most jxcore releases available to compare if necessary: https://github.com/nodenv/node-build/tree/master/share/node-build

**Comment by yaronyg** [comment]
Sorry but we don't use old binaries. We build our own. See https://github.com/thaliproject/jxbuild/blob/master/distribute.md

Note that as we find bugs we are submitting them back to JXcore.

**Comment by jasonkarns** [comment]
@yaronyg do you find jxcore's inclusion and support in nodenv/node-build worthwhile? At present, the build definitions are completely broken given the missing binaries (even the source build is broken since npmjx is no longer on S3). Unless there is some community demand/request for support, we will likely completely remove jxcore from nodenv.

**Comment by yaronyg** [comment]
@jasonkarns This is a truly tough question. The reality (as I'm sure @obastemur will confirm) is that JXcore is dead. A few of us are keeping it going as a Zombie because there really isn't any other solution for node on Android and iOS at the moment. But a Zombie isn't a living creature. So should node-build be presenting a Zombie? The only reason I don't think the answer is obvious is that if someone really does want to play with Node on Android and iOS then JXcore is the only game in town, Zombie or not. And if someone is using JXcore on iOS or Android then they are also going to need JXcore on the desktop so they can test (that is why we keep JXcore going). But, for example, although we currently have JXcore running (I believe) on Linux, OS/X and Windows we are really only committed to running it on OS/X because that is our primary dev environment. It's... a mess... Zombies always are.... body parts falling off... etc.

**Comment by jasonkarns** [comment]
This had me rolling on the floor! (All body parts remained attached, though, luckily)

I understand and agree. For node-build, the definitions are presently broken because the download links are broken. So the work to get node-build working again is strictly limited to finding pre-built assets (and since we have the old checksums, I'd feel fine to re-upload them somewhere if we ever found some that matched the checksums).

I *might* be okay updating the build definitions to point to new builds if someone wants to go to the effort of compiling new builds, but I suspect that's not really worth the effort.

**Comment by yaronyg** [comment]
So we are doing new builds and usually what we are building is mostly what is in jxcore but our builds are based on https://github.com/thaliproject/jxcore. The builds we create are what I pointed to above in https://github.com/thaliproject/jxbuild/blob/master/distribute.md

But to be clear, there is no support for these builds.

**Comment by jasonkarns** [comment]
Any chance you have old builds of npmjx? Or would be able to package new
ones from old tags? If we were able to get old tarballs of npmjx uploaded
somewhere, then at least the node-build definitions would be able to
compile jxcore from source.

**Comment by jasonkarns** [comment]
The versions (with checksums) that our build defs need:

```
https://s3.amazonaws.com/nodejx/npmjx300.tar.gz#cfb8b86a39b790cabb236aa5c8bde99e4c743579c2d0118468b3e86ed9ec6298
https://s3.amazonaws.com/nodejx/npmjx303.tar.gz#f3479e698f7d9288256b944cfb14842349364575a2819bd4d635ec79924c6368
https://s3.amazonaws.com/nodejx/npmjx304.tar.gz#e12617fe36c58c59ee5d06e99f421f21b8a3215d5d780597e5218e2c6b63f17a
https://s3.amazonaws.com/nodejx/npmjx305.tar.gz#fdefdb122e6ca0ea23a11730c7e032742a86b2c7e9e46421304bc6b7ce99a7fa
https://s3.amazonaws.com/nodejx/npmjx307.tar.gz#7b99397f17f5fdb592842ccd62e25806b2a05ae9997c4508b47412f194e8ba6e
https://s3.amazonaws.com/nodejx/npmjx310.tar.gz#3c8e1b1fed9be44c4ec6fd09e6978a29c3e466f684e2812f6762c0a6d28fb85c
https://s3.amazonaws.com/nodejx/npmjx311.tar.gz#b0a696e01db4af87c2b6978453a01e4294951dd915d4770b559cab918a20c127
```

Getting these available somewhere (even if just re-packaged) would make the source-compiles in node-build work, at least.

**Comment by yaronyg** [comment]
I don't have the old binaries and just to get JXcore building required us to create a whole new infrastructure so even if we had time to build the older versions (which we really don't, we have three pri 0 bugs on JXcore right now so the only thing we're doing with JXcore is trying to fix stuff!) I doubt the builds would match.

**Comment by ktrzeciaknubisa** [comment]
Seems like I might have them: 

```bash 
$ shasum -a 256 *.*
cfb8b86a39b790cabb236aa5c8bde99e4c743579c2d0118468b3e86ed9ec6298  npmjx300.tar.gz
f3479e698f7d9288256b944cfb14842349364575a2819bd4d635ec79924c6368  npmjx303.tar.gz
e12617fe36c58c59ee5d06e99f421f21b8a3215d5d780597e5218e2c6b63f17a  npmjx304.tar.gz
fdefdb122e6ca0ea23a11730c7e032742a86b2c7e9e46421304bc6b7ce99a7fa  npmjx305.tar.gz
7b99397f17f5fdb592842ccd62e25806b2a05ae9997c4508b47412f194e8ba6e  npmjx307.tar.gz
3c8e1b1fed9be44c4ec6fd09e6978a29c3e466f684e2812f6762c0a6d28fb85c  npmjx310.tar.gz
b0a696e01db4af87c2b6978453a01e4294951dd915d4770b559cab918a20c127  npmjx311.tar.gz
```

[npmjx300.tar.gz](https://github.com/jxcore/jxcore/files/484377/npmjx300.tar.gz)
[npmjx303.tar.gz](https://github.com/jxcore/jxcore/files/484375/npmjx303.tar.gz)
[npmjx304.tar.gz](https://github.com/jxcore/jxcore/files/484378/npmjx304.tar.gz)
[npmjx305.tar.gz](https://github.com/jxcore/jxcore/files/484374/npmjx305.tar.gz)
[npmjx307.tar.gz](https://github.com/jxcore/jxcore/files/484376/npmjx307.tar.gz)
[npmjx310.tar.gz](https://github.com/jxcore/jxcore/files/484379/npmjx310.tar.gz)
[npmjx311.tar.gz](https://github.com/jxcore/jxcore/files/484380/npmjx311.tar.gz)

**Comment by jasonkarns** [comment]
@ktrzeciaknubisa awesome! I think the best place for these would be on the releases page here on JXCore. That way they can be listed as downloads right alongside the jxcore release for which they are required.

Do you have the time to add them to the releases? I do and could, but I would need added (temporarily, of course) as a member of the repo.

**Comment by obastemur** [comment]
@jasonkarns sorry for not adding you earlier. You are the member of JXcore now. Thanks

**Comment by jasonkarns** [comment]
npmjx tarballs added to their corresponding releases on the [Releases](https://github.com/jxcore/jxcore/releases) page

**Comment by obastemur** [comment]
Thanks @jasonkarns
