### ISSUE TITLE
Installing express in jxcore

### ISSUE THREAD

**Issue by kendemu** [jxcore/jxcore#920]
Hello,

I want to use express in jxcore cordova project.
However, when I tried this command: 
```bash
$ jxc sample express_sample
```
This following error happens.
```bash
Installing npm modules for the sample...
Command failed: `"/usr/local/bin/jx" install --autoremove ".*,*.md,*.MD,*.gz"`:
Error: Command failed: "/usr/local/bin/jx" install --autoremove ".*,*.md,*.MD,*.gz"
Your package was created with older JXcore packaging format which is currently depreciated and its support will be removed in future JXcore releases.

module.js:2098
    throw err;
          ^
Error: Package is either corrupted or not compatible with this JX binary. (/home/demulab/.jx/npmjxv311.jx)
    at Object.Module._extensions..jx (module.js:2095:15)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:878:12)
    at startup (node.js:492:18)
    at node.js:1611:3
```

I also tried installing express using the jx command:
```bash
$ jx install express
```
However, same error happens.

I found this error is happening from jxcore version, but I can't install the previous jxcore because the amazonaws link is corrupt. I'm using the jxcore installed from source.
What I have to do to use express?

**Comment by kendemu** [comment]
![cordova-express](https://cloud.githubusercontent.com/assets/7846530/22416883/7726bf50-e714-11e6-9c6e-8d84c3977082.png)
I found how to solve this problem.
Don't use the jx package manager.
The important thing is, just use the npm package manager, and jxcore is just for packaging and cross-compiling node.js project to other environment.
