### ISSUE TITLE
Use of const in strict mode.

### ISSUE THREAD

**Issue by Grigoriy74** [jxcore/jxcore#925]
If I run the application through the node js, everything works well,
if received through the JXCore, I get an error:

const util = require('util');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:589:25)
    at Object.Module._extensions..js (module.js:649:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (H:\sss\extjs\JXcore\newWork\site\server.js.jx:111:10)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)

I'd like to help

**Comment by b0unc3r** [comment]
Did you find any workaround?

**Comment by Grigoriy74** [comment]
no

**Comment by sachinavinaw** [comment]
Can someone help solving this issue?

`C:\Users\SachinAvinaw\Desktop\PAKAGING\24072019-115200\node_modules\pug-lexer\index.js.jx:1220`
             `const isNotPunctuator = !characterParser.isPunctuator(str[x])`
              ^^^^^

`GET / 500 14.098 ms - 818`
`SyntaxError: Use of const in strict mode.`
    `at Module._compile (module.js:589:25)`
    `at Object.Module._extensions..jx (module.js:2027:7)`
    `at Module.load (module.js:440:36)`
    `at Function.Module._load (module.js:405:12)`
    `at Module.require (module.js:475:17)`
    `at require (module.js:493:17)`
    `at Object.<anonymous> (C:\Users\ve00ai151\Desktop\PAKAGING\24072019-115200\node_modules\pug\lib\index.js.jx:14:11)`
    `at Module._compile (module.js:619:26)`
    `at Object.Module._extensions..jx (module.js:2027:7)`
    `at Module.load (module.js:440:36)`
