### ISSUE TITLE
Bundle error for a project with graphQl

### ISSUE THREAD

**Issue by SahanDll** [jxcore/jxcore#946]
I'm trying to bundle Nodejs project which contain graphql, but it gives below error.

var resolvedPromise = Promise.resolve()                      ^
ReferenceError: Promise is not defined
    at Object.<anonymous> (D:\WorkSpace\AAA\node_modules\graphql-server-core\src\runQuery.ts:55:25)
    at Module._compile (module.js:619:26)
    at Module._extensions..js (module.js:649:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\WorkSpace\AAA\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (D:\WorkSpace\AAA\node_modules\graphql-server-core\src\index.ts:1:1)
    at Module._compile (module.js:619:26)

**Comment by Kamaropoulos** [comment]
JXCore uses Node v0.10.40 which unfortunately doesn't support Promises.

![image](https://user-images.githubusercontent.com/10237776/57283085-05320100-70b7-11e9-9897-a3ebec69fb64.png)
